import '../../login/model/client_model.dart';

int? _asInt(dynamic value) {
  if (value == null) return null;
  if (value is int) return value;
  if (value is num) return value.toInt();
  return int.tryParse(value.toString());
}

double? _asDouble(dynamic value) {
  if (value == null) return null;
  if (value is double) return value;
  if (value is num) return value.toDouble();
  return double.tryParse(value.toString());
}

Map<String, dynamic>? _asMap(dynamic value) {
  if (value is Map) return Map<String, dynamic>.from(value);
  return null;
}

List<dynamic> _asList(dynamic value) {
  if (value is List) return value;
  return const [];
}

dynamic _firstValue(Map<String, dynamic> json, List<String> keys) {
  for (final key in keys) {
    if (json[key] != null) return json[key];
  }
  return null;
}

List<dynamic>? _extractVehicleList(Map<String, dynamic> json) {
  const listKeys = [
    'vehicleStatusdetails',
    'vehicleStatusDetails',
    'VehicleStatusdetails',
    'vehicles',
    'vehicleList',
    'vehicleDetails',
    'vehicledetails',
    'pinvehicle',
    'Pinvehicle',
    'result',
    'Result',
  ];
  for (final key in listKeys) {
    final value = json[key];
    if (value is List) return value;
  }
  final nested = json['data'] ?? json['Data'];
  if (nested is List) return nested;
  final nestedMap = _asMap(nested);
  if (nestedMap != null) return _extractVehicleList(nestedMap);
  return null;
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AlertListResponseModelDataVehicleCount {
/*
{
  "recCnt": 44
} 
*/

  int? recCnt;

  AlertListResponseModelDataVehicleCount({
    this.recCnt,
  });
  AlertListResponseModelDataVehicleCount.fromJson(Map<String, dynamic> json) {
    recCnt = _asInt(_firstValue(json, [
      'recCnt',
      'RecCnt',
      'recCount',
      'reccount',
      'totRec',
      'TotRec',
    ]));
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['recCnt'] = recCnt;
    return data;
  }
}

class VehicleStatusResponseModelDataVehicleStatusdetails {
/*
{
  "id": 1,
  "Vehicleid": 38,
  "Clientid": 20,
  "VehicleNo": "91004",
  "unitno": "91004",
  "tracktime": "2022-12-27T18:22:00.000Z",
  "lat": 12.991003036499023,
  "lon": 77.58885955810547,
  "location": "on Buildings A, Cunningham Rd, Vasanth Nagar, Bengaluru, Karnataka 560051 インド",
  "ignition": 0,
  "speed": 0,
  "odometer": 1575.94,
  "direction": 357,
  "idleduration": 91,
  "stopduration": 0,
  "alertind": 0,
  "EngineOffdelay": 0,
  "Directions": 0,
  "Status": "Inactive",
  "LiveUrl": "https://uyenotestlivevideo.infotracktelematics.com:9965/vss/apiPage/RealVideo.html?token==21232f297a57a5a743894a0e4a801fc3&deviceId=91004&chs=1_2_3_4&stream=0&wnum=4&panel=1",
  "vstatus": "All Vehicles"
} 
*/

  int? id;
  int? Vehicleid;
  int? Clientid;
  String? VehicleNo;
  String? unitno;
  String? tracktime;
  double? lat;
  double? lon;
  String? location;
  int? ignition;
  int? speed;
  double? odometer;
  int? direction;
  int? idleduration;
  int? stopduration;
  int? alertind;
  int? EngineOffdelay;
  int? Directions;
  String? Status;
  String? LiveUrl;
  String? vstatus;
  int? IsPinVehicle;
  int? alertTypeId;
  String? devicetype;

  VehicleStatusResponseModelDataVehicleStatusdetails(
      {this.id,
      this.Vehicleid,
      this.Clientid,
      this.VehicleNo,
      this.unitno,
      this.tracktime,
      this.lat,
      this.lon,
      this.location,
      this.ignition,
      this.speed,
      this.odometer,
      this.direction,
      this.idleduration,
      this.stopduration,
      this.alertind,
      this.EngineOffdelay,
      this.Directions,
      this.Status,
      this.LiveUrl,
      this.vstatus,
      this.IsPinVehicle,
      this.alertTypeId,
      this.devicetype
      });
  VehicleStatusResponseModelDataVehicleStatusdetails.fromJson(
      Map<String, dynamic> json) {
    id = _asInt(json['id']);
    Vehicleid = _asInt(_firstValue(json, [
      'Vehicleid',
      'vehicleId',
      'VehicleId',
      'VehicleID',
    ]));
    Clientid = _asInt(_firstValue(json, ['Clientid', 'clientId', 'ClientId']));
    VehicleNo =
        _firstValue(json, ['VehicleNo', 'vehicleNo', 'vehicleNumber'])
            ?.toString();
    unitno = _firstValue(json, ['unitno', 'unitNo', 'Unitno', 'UnitNo'])
        ?.toString();
    tracktime = _firstValue(json, [
      'tracktime',
      'trackTime',
      'TrackingTime',
      'trackingTime',
    ])?.toString();
    lat = _asDouble(_firstValue(json, ['Lat', 'lat', 'latitude']));
    lon = _asDouble(
        _firstValue(json, ['lon', 'Lon', 'lng', 'Lng', 'longitude']));
    final mapit =
        _firstValue(json, ['Mapit', 'mapit', 'mapIt'])?.toString();
    if ((lat == null || lon == null) &&
        mapit != null &&
        mapit.contains(',')) {
      final parts = mapit.split(',');
      lat ??= double.tryParse(parts[0].trim());
      if (parts.length > 1) lon ??= double.tryParse(parts[1].trim());
    }
    location = _firstValue(json, ['location', 'Location'])?.toString();
    final rawIgnition = json['ignition'];
    if (rawIgnition is String) {
      ignition = rawIgnition.toLowerCase() == 'on' || rawIgnition == '1'
          ? 1
          : 0;
    } else {
      ignition = _asInt(rawIgnition);
    }
    speed = _asInt(json['speed']);
    odometer = _asDouble(json['odometer']);
    direction = _asInt(json['direction']);
    idleduration = _asInt(_firstValue(
        json, ['idleduration', 'idleDuration', 'Idleduration']));
    stopduration =
        _asInt(_firstValue(json, ['stopduration', 'stopDuration']));
    alertind = _asInt(_firstValue(json, ['alertind', 'alertInd']));
    EngineOffdelay =
        _asInt(_firstValue(json, ['EngineOffdelay', 'engineOffdelay']));
    Directions = _asInt(json['Directions']);
    Status = _firstValue(json, ['Status', 'status', 'vstatus'])?.toString();
    LiveUrl = _firstValue(json, ['LiveUrl', 'liveUrl'])?.toString();
    vstatus = _firstValue(json, ['vstatus', 'vStatus'])?.toString();
    IsPinVehicle =
        _asInt(_firstValue(json, ['IsPinVehicle', 'isPinVehicle']));
    devicetype =
        _firstValue(json, ['devicetype', 'deviceType'])?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['Vehicleid'] = Vehicleid;
    data['Clientid'] = Clientid;
    data['VehicleNo'] = VehicleNo;
    data['unitno'] = unitno;
    data['tracktime'] = tracktime;
    data['lat'] = lat;
    data['lon'] = lon;
    data['location'] = location;
    data['ignition'] = ignition;
    data['speed'] = speed;
    data['odometer'] = odometer;
    data['direction'] = direction;
    data['idleduration'] = idleduration;
    data['stopduration'] = stopduration;
    data['alertind'] = alertind;
    data['EngineOffdelay'] = EngineOffdelay;
    data['Directions'] = Directions;
    data['Status'] = Status;
    data['LiveUrl'] = LiveUrl;
    data['vstatus'] = vstatus;
    data['IsPinVehicle'] = IsPinVehicle;
    data['deviceType'] = devicetype;
    return data;
  }
}

class VehicleStatusResponseModelData {
/*
{
  "status": 200,
  "vehicleStatusdetails": [
    {
      "id": 1,
      "Vehicleid": 38,
      "Clientid": 20,
      "VehicleNo": "91004",
      "unitno": "91004",
      "tracktime": "2022-12-27T18:22:00.000Z",
      "lat": 12.991003036499023,
      "lon": 77.58885955810547,
      "location": "on Buildings A, Cunningham Rd, Vasanth Nagar, Bengaluru, Karnataka 560051 インド",
      "ignition": 0,
      "speed": 0,
      "odometer": 1575.94,
      "direction": 357,
      "idleduration": 91,
      "stopduration": 0,
      "alertind": 0,
      "EngineOffdelay": 0,
      "Directions": 0,
      "Status": "Inactive",
      "LiveUrl": "https://uyenotestlivevideo.infotracktelematics.com:9965/vss/apiPage/RealVideo.html?token==21232f297a57a5a743894a0e4a801fc3&deviceId=91004&chs=1_2_3_4&stream=0&wnum=4&panel=1",
      "vstatus": "All Vehicles"
    }
  ]
} 
*/

  int? status;
  List<VehicleStatusResponseModelDataVehicleStatusdetails?>?
      vehicleStatusdetails;
  List<DataError?>? error;
  List<AlertListResponseModelDataVehicleCount?>? vehicleCount;

  VehicleStatusResponseModelData(
      {this.status, this.vehicleStatusdetails, this.vehicleCount, this.error});
  VehicleStatusResponseModelData.fromJson(Map<String, dynamic> json) {
    status = _asInt(json['status'] ?? json['Status']);
    final detailsRaw = _extractVehicleList(json);
    if (detailsRaw != null) {
      vehicleStatusdetails = detailsRaw
          .whereType<Map>()
          .map((item) => VehicleStatusResponseModelDataVehicleStatusdetails
              .fromJson(Map<String, dynamic>.from(item)))
          .toList();
    }
    final countRaw = json['vehicleCount'] ??
        json['vehicleCnt'] ??
        json['VehicleCount'] ??
        _asMap(json['data'])?['vehicleCount'] ??
        _asMap(json['data'])?['vehicleCnt'];
    if (countRaw is List) {
      vehicleCount = _asList(countRaw)
          .whereType<Map>()
          .map((item) => AlertListResponseModelDataVehicleCount.fromJson(
                Map<String, dynamic>.from(item),
              ))
          .toList();
    } else {
      final rec = _asInt(_firstValue(json, [
        'recCnt',
        'recCount',
        'totalCount',
        'totRec',
        'TotRec',
      ]));
      if (rec != null) {
        vehicleCount = [AlertListResponseModelDataVehicleCount(recCnt: rec)];
      }
    }
    if (json['error'] != null) {
      vehicleCount ??= [];
      error = _asList(json['error'])
          .whereType<Map>()
          .map((item) => DataError.fromJson(Map<String, dynamic>.from(item)))
          .toList();
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (vehicleStatusdetails != null) {
      final v = vehicleStatusdetails;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['vehicleStatusdetails'] = arr0;
    }
    return data;
  }
}

class VehicleStatusResponseModel {
/*
{
  "data": {
    "status": 200,
    "vehicleStatusdetails": [
      {
        "id": 1,
        "Vehicleid": 38,
        "Clientid": 20,
        "VehicleNo": "91004",
        "unitno": "91004",
        "tracktime": "2022-12-27T18:22:00.000Z",
        "lat": 12.991003036499023,
        "lon": 77.58885955810547,
        "location": "on Buildings A, Cunningham Rd, Vasanth Nagar, Bengaluru, Karnataka 560051 インド",
        "ignition": 0,
        "speed": 0,
        "odometer": 1575.94,
        "direction": 357,
        "idleduration": 91,
        "stopduration": 0,
        "alertind": 0,
        "EngineOffdelay": 0,
        "Directions": 0,
        "Status": "Inactive",
        "LiveUrl": "https://uyenotestlivevideo.infotracktelematics.com:9965/vss/apiPage/RealVideo.html?token==21232f297a57a5a743894a0e4a801fc3&deviceId=91004&chs=1_2_3_4&stream=0&wnum=4&panel=1",
        "vstatus": "All Vehicles"
      }
    ]
  }
} 
*/

  VehicleStatusResponseModelData? data;

  VehicleStatusResponseModel({
    this.data,
  });
  VehicleStatusResponseModel.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null && json['data'] is Map) {
      data = VehicleStatusResponseModelData.fromJson(
        Map<String, dynamic>.from(json['data'] as Map),
      );
    } else {
      data = VehicleStatusResponseModelData.fromJson(json);
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data!.toJson();
    return data;
  }
}
