import '../../../utils/json_safe_parser.dart';
import '../../login/model/client_model.dart';

List<dynamic>? _extractVehicleList(Map<String, dynamic> json) {
  const listKeys = [
    'vehicleStatusdetails',
    'vehicleStatusDetails',
    'VehicleStatusdetails',
    'vehicles',
    'vehicleList',
    'vehicleDetails',
    'vehicledetails',
    'pinvehicle',
    'Pinvehicle',
    'result',
    'Result',
  ];
  final fromKeys = JsonSafe.asListOrNull(JsonSafe.firstValue(json, listKeys));
  if (fromKeys != null) return fromKeys;
  final nested = JsonSafe.firstValue(json, ['data', 'Data']);
  final nestedList = JsonSafe.asListOrNull(nested);
  if (nestedList != null) return nestedList;
  final nestedMap = JsonSafe.asMapOrNull(nested);
  if (nestedMap != null) return _extractVehicleList(nestedMap);
  return null;
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AlertListResponseModelDataVehicleCount with JsonSafeParser {
/*
{
  "recCnt": 44
} 
*/

  int? recCnt;

  AlertListResponseModelDataVehicleCount({
    this.recCnt,
  });
  AlertListResponseModelDataVehicleCount.fromJson(Map<String, dynamic> json) {
    recCnt = asIntFrom(json, [
      'recCnt',
      'RecCnt',
      'recCount',
      'reccount',
      'totRec',
      'TotRec',
    ]);
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['recCnt'] = recCnt;
    return data;
  }
}

class VehicleStatusResponseModelDataVehicleStatusdetails with JsonSafeParser {
/*
{
  "id": 1,
  "Vehicleid": 38,
  "Clientid": 20,
  "VehicleNo": "91004",
  "unitno": "91004",
  "tracktime": "2022-12-27T18:22:00.000Z",
  "lat": 12.991003036499023,
  "lon": 77.58885955810547,
  "location": "on Buildings A, Cunningham Rd, Vasanth Nagar, Bengaluru, Karnataka 560051 インド",
  "ignition": 0,
  "speed": 0,
  "odometer": 1575.94,
  "direction": 357,
  "idleduration": 91,
  "stopduration": 0,
  "alertind": 0,
  "EngineOffdelay": 0,
  "Directions": 0,
  "Status": "Inactive",
  "LiveUrl": "https://uyenotestlivevideo.infotracktelematics.com:9965/vss/apiPage/RealVideo.html?token==21232f297a57a5a743894a0e4a801fc3&deviceId=91004&chs=1_2_3_4&stream=0&wnum=4&panel=1",
  "vstatus": "All Vehicles"
} 
*/

  int? id;
  int? Vehicleid;
  int? Clientid;
  String? VehicleNo;
  String? unitno;
  String? tracktime;
  double? lat;
  double? lon;
  String? location;
  int? ignition;
  int? speed;
  double? odometer;
  int? direction;
  int? idleduration;
  int? stopduration;
  int? alertind;
  int? EngineOffdelay;
  int? Directions;
  String? Status;
  String? LiveUrl;
  String? vstatus;
  int? IsPinVehicle;
  int? alertTypeId;
  String? devicetype;

  VehicleStatusResponseModelDataVehicleStatusdetails(
      {this.id,
      this.Vehicleid,
      this.Clientid,
      this.VehicleNo,
      this.unitno,
      this.tracktime,
      this.lat,
      this.lon,
      this.location,
      this.ignition,
      this.speed,
      this.odometer,
      this.direction,
      this.idleduration,
      this.stopduration,
      this.alertind,
      this.EngineOffdelay,
      this.Directions,
      this.Status,
      this.LiveUrl,
      this.vstatus,
      this.IsPinVehicle,
      this.alertTypeId,
      this.devicetype
      });
  VehicleStatusResponseModelDataVehicleStatusdetails.fromJson(
      Map<String, dynamic> json) {
    id = asInt(json['id']);
    Vehicleid = asIntFrom(json, [
      'Vehicleid',
      'vehicleId',
      'VehicleId',
      'VehicleID',
    ]);
    Clientid = asIntFrom(json, ['Clientid', 'clientId', 'ClientId']);
    VehicleNo = asStringFrom(json, ['VehicleNo', 'vehicleNo', 'vehicleNumber']);
    unitno = asStringFrom(json, ['unitno', 'unitNo', 'Unitno', 'UnitNo']);
    tracktime = asStringFrom(json, [
      'tracktime',
      'trackTime',
      'TrackingTime',
      'trackingTime',
    ]);
    lat = asDoubleOrNull(firstValue(json, ['Lat', 'lat', 'latitude']));
    lon = asDoubleOrNull(
        firstValue(json, ['lon', 'Lon', 'lng', 'Lng', 'longitude']));
    final mapit = asStringOrNull(firstValue(json, ['Mapit', 'mapit', 'mapIt']));
    if ((lat == null || lon == null) &&
        mapit != null &&
        mapit.contains(',')) {
      final parts = mapit.split(',');
      lat ??= double.tryParse(parts[0].trim());
      if (parts.length > 1) lon ??= double.tryParse(parts[1].trim());
    }
    location = asStringFrom(json, ['location', 'Location']);
    final rawIgnition = json['ignition'];
    if (rawIgnition is String) {
      ignition = rawIgnition.toLowerCase() == 'on' || rawIgnition == '1'
          ? 1
          : 0;
    } else {
      ignition = asInt(rawIgnition);
    }
    speed = asInt(json['speed']);
    odometer = asDouble(json['odometer']);
    direction = asInt(json['direction']);
    idleduration =
        asIntFrom(json, ['idleduration', 'idleDuration', 'Idleduration']);
    stopduration = asIntFrom(json, ['stopduration', 'stopDuration']);
    alertind = asIntFrom(json, ['alertind', 'alertInd']);
    EngineOffdelay = asIntFrom(json, ['EngineOffdelay', 'engineOffdelay']);
    Directions = asInt(json['Directions']);
    Status = asStringFrom(json, ['Status', 'status', 'vstatus']);
    LiveUrl = asStringFrom(json, ['LiveUrl', 'liveUrl']);
    vstatus = asStringFrom(json, ['vstatus', 'vStatus']);
    IsPinVehicle = asIntFrom(json, ['IsPinVehicle', 'isPinVehicle']);
    devicetype = asStringFrom(json, ['devicetype', 'deviceType']);
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['Vehicleid'] = Vehicleid;
    data['Clientid'] = Clientid;
    data['VehicleNo'] = VehicleNo;
    data['unitno'] = unitno;
    data['tracktime'] = tracktime;
    data['lat'] = lat;
    data['lon'] = lon;
    data['location'] = location;
    data['ignition'] = ignition;
    data['speed'] = speed;
    data['odometer'] = odometer;
    data['direction'] = direction;
    data['idleduration'] = idleduration;
    data['stopduration'] = stopduration;
    data['alertind'] = alertind;
    data['EngineOffdelay'] = EngineOffdelay;
    data['Directions'] = Directions;
    data['Status'] = Status;
    data['LiveUrl'] = LiveUrl;
    data['vstatus'] = vstatus;
    data['IsPinVehicle'] = IsPinVehicle;
    data['deviceType'] = devicetype;
    return data;
  }
}

class VehicleStatusResponseModelData with JsonSafeParser {
/*
{
  "status": 200,
  "vehicleStatusdetails": [
    {
      "id": 1,
      "Vehicleid": 38,
      "Clientid": 20,
      "VehicleNo": "91004",
      "unitno": "91004",
      "tracktime": "2022-12-27T18:22:00.000Z",
      "lat": 12.991003036499023,
      "lon": 77.58885955810547,
      "location": "on Buildings A, Cunningham Rd, Vasanth Nagar, Bengaluru, Karnataka 560051 インド",
      "ignition": 0,
      "speed": 0,
      "odometer": 1575.94,
      "direction": 357,
      "idleduration": 91,
      "stopduration": 0,
      "alertind": 0,
      "EngineOffdelay": 0,
      "Directions": 0,
      "Status": "Inactive",
      "LiveUrl": "https://uyenotestlivevideo.infotracktelematics.com:9965/vss/apiPage/RealVideo.html?token==21232f297a57a5a743894a0e4a801fc3&deviceId=91004&chs=1_2_3_4&stream=0&wnum=4&panel=1",
      "vstatus": "All Vehicles"
    }
  ]
} 
*/

  int? status;
  List<VehicleStatusResponseModelDataVehicleStatusdetails?>?
      vehicleStatusdetails;
  List<DataError?>? error;
  List<AlertListResponseModelDataVehicleCount?>? vehicleCount;

  VehicleStatusResponseModelData(
      {this.status, this.vehicleStatusdetails, this.vehicleCount, this.error});
  VehicleStatusResponseModelData.fromJson(Map<String, dynamic> json) {
    status = asIntFrom(json, ['status', 'Status']);
    final detailsRaw = _extractVehicleList(json);
    if (detailsRaw != null) {
      vehicleStatusdetails = asListOfMaps(detailsRaw)
          .map(VehicleStatusResponseModelDataVehicleStatusdetails.fromJson)
          .toList();
    }
    final nestedData = asMapOrNull(json['data']);
    final countRaw = asListOrNull(firstValue(json, [
          'vehicleCount',
          'vehicleCnt',
          'VehicleCount',
        ])) ??
        asListOrNull(firstValue(nestedData ?? const {}, [
          'vehicleCount',
          'vehicleCnt',
        ]));
    if (countRaw != null) {
      vehicleCount = asListOfMaps(countRaw)
          .map(AlertListResponseModelDataVehicleCount.fromJson)
          .toList();
    } else {
      final rec = asIntOrNull(firstValue(json, [
        'recCnt',
        'recCount',
        'totalCount',
        'totRec',
        'TotRec',
      ]));
      if (rec != null) {
        vehicleCount = [AlertListResponseModelDataVehicleCount(recCnt: rec)];
      }
    }
    if (json['error'] != null) {
      vehicleCount ??= [];
      error = asListOfMaps(json['error']).map(DataError.fromJson).toList();
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (vehicleStatusdetails != null) {
      final v = vehicleStatusdetails;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['vehicleStatusdetails'] = arr0;
    }
    return data;
  }
}

class VehicleStatusResponseModel with JsonSafeParser {
/*
{
  "data": {
    "status": 200,
    "vehicleStatusdetails": [
      {
        "id": 1,
        "Vehicleid": 38,
        "Clientid": 20,
        "VehicleNo": "91004",
        "unitno": "91004",
        "tracktime": "2022-12-27T18:22:00.000Z",
        "lat": 12.991003036499023,
        "lon": 77.58885955810547,
        "location": "on Buildings A, Cunningham Rd, Vasanth Nagar, Bengaluru, Karnataka 560051 インド",
        "ignition": 0,
        "speed": 0,
        "odometer": 1575.94,
        "direction": 357,
        "idleduration": 91,
        "stopduration": 0,
        "alertind": 0,
        "EngineOffdelay": 0,
        "Directions": 0,
        "Status": "Inactive",
        "LiveUrl": "https://uyenotestlivevideo.infotracktelematics.com:9965/vss/apiPage/RealVideo.html?token==21232f297a57a5a743894a0e4a801fc3&deviceId=91004&chs=1_2_3_4&stream=0&wnum=4&panel=1",
        "vstatus": "All Vehicles"
      }
    ]
  }
} 
*/

  VehicleStatusResponseModelData? data;

  VehicleStatusResponseModel({
    this.data,
  });
  VehicleStatusResponseModel.fromJson(Map<String, dynamic> json) {
    final dataMap = asMapOrNull(json['data']);
    if (dataMap != null) {
      data = VehicleStatusResponseModelData.fromJson(dataMap);
    } else {
      data = VehicleStatusResponseModelData.fromJson(json);
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data!.toJson();
    return data;
  }
}
