import '../../login/model/client_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AlertListResponseModelDataVehicleCount {
/*
{
  "recCnt": 44
} 
*/

  int? recCnt;

  AlertListResponseModelDataVehicleCount({
    this.recCnt,
  });
  AlertListResponseModelDataVehicleCount.fromJson(Map<String, dynamic> json) {
    recCnt = json['recCnt']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['recCnt'] = recCnt;
    return data;
  }
}

class VehicleStatusResponseModelDataVehicleStatusdetails {
/*
{
  "id": 1,
  "Vehicleid": 38,
  "Clientid": 20,
  "VehicleNo": "91004",
  "unitno": "91004",
  "tracktime": "2022-12-27T18:22:00.000Z",
  "lat": 12.991003036499023,
  "lon": 77.58885955810547,
  "location": "on Buildings A, Cunningham Rd, Vasanth Nagar, Bengaluru, Karnataka 560051 インド",
  "ignition": 0,
  "speed": 0,
  "odometer": 1575.94,
  "direction": 357,
  "idleduration": 91,
  "stopduration": 0,
  "alertind": 0,
  "EngineOffdelay": 0,
  "Directions": 0,
  "Status": "Inactive",
  "LiveUrl": "https://uyenotestlivevideo.infotracktelematics.com:9965/vss/apiPage/RealVideo.html?token==21232f297a57a5a743894a0e4a801fc3&deviceId=91004&chs=1_2_3_4&stream=0&wnum=4&panel=1",
  "vstatus": "All Vehicles"
} 
*/

  int? id;
  int? Vehicleid;
  int? Clientid;
  String? VehicleNo;
  String? unitno;
  String? tracktime;
  double? lat;
  double? lon;
  String? location;
  int? ignition;
  int? speed;
  double? odometer;
  int? direction;
  int? idleduration;
  int? stopduration;
  int? alertind;
  int? EngineOffdelay;
  int? Directions;
  String? Status;
  String? LiveUrl;
  String? vstatus;
  int? IsPinVehicle;
  int? alertTypeId;
  String? devicetype;

  VehicleStatusResponseModelDataVehicleStatusdetails(
      {this.id,
      this.Vehicleid,
      this.Clientid,
      this.VehicleNo,
      this.unitno,
      this.tracktime,
      this.lat,
      this.lon,
      this.location,
      this.ignition,
      this.speed,
      this.odometer,
      this.direction,
      this.idleduration,
      this.stopduration,
      this.alertind,
      this.EngineOffdelay,
      this.Directions,
      this.Status,
      this.LiveUrl,
      this.vstatus,
      this.IsPinVehicle,
      this.alertTypeId,
      this.devicetype
      });
  VehicleStatusResponseModelDataVehicleStatusdetails.fromJson(
      Map<String, dynamic> json) {
    id = json['id']?.toInt();
    Vehicleid = json['Vehicleid']?.toInt();
    Clientid = json['Clientid']?.toInt();
    VehicleNo = json['VehicleNo']?.toString();
    unitno = json['unitno']?.toString();
    tracktime = json['tracktime']?.toString();
    lat = json['Lat']?.toDouble();
    lon = json['lon']?.toDouble();
    location = json['location']?.toString();
    ignition = json['ignition']?.toInt();
    speed = json['speed']?.toInt();
    odometer = json['odometer']?.toDouble();
    direction = json['direction']?.toInt();
    idleduration = json['idleduration']?.toInt();
    stopduration = json['stopduration']?.toInt();
    alertind = json['alertind']?.toInt();
    EngineOffdelay = json['EngineOffdelay']?.toInt();
    Directions = json['Directions']?.toInt();
    Status = json['Status']?.toString();
    LiveUrl = json['LiveUrl']?.toString();
    vstatus = json['vstatus']?.toString();
    IsPinVehicle = json['IsPinVehicle']?.toInt();
    devicetype = json['devicetype']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['Vehicleid'] = Vehicleid;
    data['Clientid'] = Clientid;
    data['VehicleNo'] = VehicleNo;
    data['unitno'] = unitno;
    data['tracktime'] = tracktime;
    data['lat'] = lat;
    data['lon'] = lon;
    data['location'] = location;
    data['ignition'] = ignition;
    data['speed'] = speed;
    data['odometer'] = odometer;
    data['direction'] = direction;
    data['idleduration'] = idleduration;
    data['stopduration'] = stopduration;
    data['alertind'] = alertind;
    data['EngineOffdelay'] = EngineOffdelay;
    data['Directions'] = Directions;
    data['Status'] = Status;
    data['LiveUrl'] = LiveUrl;
    data['vstatus'] = vstatus;
    data['IsPinVehicle'] = IsPinVehicle;
    data['deviceType'] = devicetype;
    return data;
  }
}

class VehicleStatusResponseModelData {
/*
{
  "status": 200,
  "vehicleStatusdetails": [
    {
      "id": 1,
      "Vehicleid": 38,
      "Clientid": 20,
      "VehicleNo": "91004",
      "unitno": "91004",
      "tracktime": "2022-12-27T18:22:00.000Z",
      "lat": 12.991003036499023,
      "lon": 77.58885955810547,
      "location": "on Buildings A, Cunningham Rd, Vasanth Nagar, Bengaluru, Karnataka 560051 インド",
      "ignition": 0,
      "speed": 0,
      "odometer": 1575.94,
      "direction": 357,
      "idleduration": 91,
      "stopduration": 0,
      "alertind": 0,
      "EngineOffdelay": 0,
      "Directions": 0,
      "Status": "Inactive",
      "LiveUrl": "https://uyenotestlivevideo.infotracktelematics.com:9965/vss/apiPage/RealVideo.html?token==21232f297a57a5a743894a0e4a801fc3&deviceId=91004&chs=1_2_3_4&stream=0&wnum=4&panel=1",
      "vstatus": "All Vehicles"
    }
  ]
} 
*/

  int? status;
  List<VehicleStatusResponseModelDataVehicleStatusdetails?>?
      vehicleStatusdetails;
  List<DataError?>? error;
  List<AlertListResponseModelDataVehicleCount?>? vehicleCount;

  VehicleStatusResponseModelData(
      {this.status, this.vehicleStatusdetails, this.vehicleCount, this.error});
  VehicleStatusResponseModelData.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    if (json['vehicleStatusdetails'] != null) {
      final v = json['vehicleStatusdetails'];
      final arr0 = <VehicleStatusResponseModelDataVehicleStatusdetails>[];
      v.forEach((v) {
        arr0.add(
            VehicleStatusResponseModelDataVehicleStatusdetails.fromJson(v));
      });
      vehicleStatusdetails = arr0;
    }
    if (json['vehicleCount'] != null) {
      final v = json['vehicleCount'];
      final arr0 = <AlertListResponseModelDataVehicleCount>[];
      v.forEach((v) {
        arr0.add(AlertListResponseModelDataVehicleCount.fromJson(v));
      });
      vehicleCount = arr0;
    }
    if (json['error'] != null) {
      final v = json['error'];
      final arr0 = <DataError>[];
      v.forEach((v) {
        arr0.add(DataError.fromJson(v));
      });
      error = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (vehicleStatusdetails != null) {
      final v = vehicleStatusdetails;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['vehicleStatusdetails'] = arr0;
    }
    return data;
  }
}

class VehicleStatusResponseModel {
/*
{
  "data": {
    "status": 200,
    "vehicleStatusdetails": [
      {
        "id": 1,
        "Vehicleid": 38,
        "Clientid": 20,
        "VehicleNo": "91004",
        "unitno": "91004",
        "tracktime": "2022-12-27T18:22:00.000Z",
        "lat": 12.991003036499023,
        "lon": 77.58885955810547,
        "location": "on Buildings A, Cunningham Rd, Vasanth Nagar, Bengaluru, Karnataka 560051 インド",
        "ignition": 0,
        "speed": 0,
        "odometer": 1575.94,
        "direction": 357,
        "idleduration": 91,
        "stopduration": 0,
        "alertind": 0,
        "EngineOffdelay": 0,
        "Directions": 0,
        "Status": "Inactive",
        "LiveUrl": "https://uyenotestlivevideo.infotracktelematics.com:9965/vss/apiPage/RealVideo.html?token==21232f297a57a5a743894a0e4a801fc3&deviceId=91004&chs=1_2_3_4&stream=0&wnum=4&panel=1",
        "vstatus": "All Vehicles"
      }
    ]
  }
} 
*/

  VehicleStatusResponseModelData? data;

  VehicleStatusResponseModel({
    this.data,
  });
  VehicleStatusResponseModel.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? VehicleStatusResponseModelData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data!.toJson();
    return data;
  }
}
