import '../../login/model/client_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetCountriesResponseModelDataCountryList {
/*
{
  "id": 104,
  "CountryName": "India",
  "isActive": true
} 
*/

  int? id;
  String? CountryName;
  bool? isActive;

  GetCountriesResponseModelDataCountryList({
    this.id,
    this.CountryName,
    this.isActive,
  });
  GetCountriesResponseModelDataCountryList.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    CountryName = json['CountryName']?.toString();
    isActive = json['isActive'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['CountryName'] = CountryName;
    data['isActive'] = isActive;
    return data;
  }
}

class GetCountriesResponseModelData {
/*
{
  "status": 200,
  "countryList": [
    {
      "id": 104,
      "CountryName": "India",
      "isActive": true
    }
  ]
} 
*/

  int? status;
  List<GetCountriesResponseModelDataCountryList?>? countryList = [];
  List<DataError?>? error;

  GetCountriesResponseModelData({this.status, this.countryList, this.error});
  GetCountriesResponseModelData.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    final countriesJson = json['countryList'] ?? json['deleteClientData'];
    if (countriesJson != null) {
      final v = countriesJson;
      final arr0 = <GetCountriesResponseModelDataCountryList>[];
      v.forEach((v) {
        arr0.add(GetCountriesResponseModelDataCountryList.fromJson(v));
      });
      countryList = arr0;
    }

    if (json['error'] != null) {
      final v = json['error'];
      final arr0 = <DataError>[];
      v.forEach((v) {
        arr0.add(DataError.fromJson(v));
      });
      error = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (countryList != null) {
      final v = countryList;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['countryList'] = arr0;
    }
    return data;
  }
}

class GetCountriesResponseModel {
/*
{
  "data": {
    "status": 200,
    "countryList": [
      {
        "id": 104,
        "CountryName": "India",
        "isActive": true
      }
    ]
  }
} 
*/

  GetCountriesResponseModelData? data;

  GetCountriesResponseModel({
    this.data,
  });
  GetCountriesResponseModel.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? GetCountriesResponseModelData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data!.toJson();
    return data;
  }
}
