import '../../../utils/json_safe_parser.dart';
import '../../login/model/client_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetCountriesResponseModelDataCountryList with JsonSafeParser {
/*
{
  "id": 104,
  "CountryName": "India",
  "isActive": true
} 
*/

  int? id;
  String? CountryName;
  bool? isActive;

  GetCountriesResponseModelDataCountryList({
    this.id,
    this.CountryName,
    this.isActive,
  });
  GetCountriesResponseModelDataCountryList.fromJson(Map<String, dynamic> json) {
    id = asInt(json['id']);
    CountryName = asStringFrom(json, ['CountryName', 'countryName']);
    isActive = asBool(json['isActive']);
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['CountryName'] = CountryName;
    data['isActive'] = isActive;
    return data;
  }
}

class GetCountriesResponseModelData with JsonSafeParser {
/*
{
  "status": 200,
  "countryList": [
    {
      "id": 104,
      "CountryName": "India",
      "isActive": true
    }
  ]
} 
*/

  int? status;
  List<GetCountriesResponseModelDataCountryList?>? countryList = [];
  List<DataError?>? error;

  GetCountriesResponseModelData({this.status, this.countryList, this.error});
  GetCountriesResponseModelData.fromJson(Map<String, dynamic> json) {
    status = asIntFrom(json, ['status', 'Status']);
    final countriesJson = json['countryList'] ?? json['deleteClientData'];
    if (countriesJson != null) {
      countryList = asListOfMaps(countriesJson)
          .map(GetCountriesResponseModelDataCountryList.fromJson)
          .toList();
    }

    if (json['error'] != null) {
      error = asListOfMaps(json['error']).map(DataError.fromJson).toList();
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (countryList != null) {
      final v = countryList;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['countryList'] = arr0;
    }
    return data;
  }
}

class GetCountriesResponseModel with JsonSafeParser {
/*
{
  "data": {
    "status": 200,
    "countryList": [
      {
        "id": 104,
        "CountryName": "India",
        "isActive": true
      }
    ]
  }
} 
*/

  GetCountriesResponseModelData? data;

  GetCountriesResponseModel({
    this.data,
  });
  GetCountriesResponseModel.fromJson(Map<String, dynamic> json) {
    final dataMap = asMapOrNull(json['data']);
    data = dataMap != null
        ? GetCountriesResponseModelData.fromJson(dataMap)
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data!.toJson();
    return data;
  }
}
