// class LanguageModel {
//   final String? title;
//   final String? subTitle;
//   bool? isSelected;
//   final String? image;
//   final String? languageCode;
//   final String? countryCode;

//   LanguageModel(
//       {this.title,
//       this.countryCode,
//       this.subTitle,
//       this.isSelected = false,
//       this.image,
//       this.languageCode});
// }

import '../../../utils/json_safe_parser.dart';
import '../../login/model/client_model.dart';

class Language {
  final String? langCode;

  // final String? countryCode;

  Language({required this.langCode});
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LanguageResponseModelDataLangListData with JsonSafeParser {
/*
{
  "languageId": 252,
  "Country_Id": 104,
  "Language": "English",
  "isActive": true
} 
*/

  int? languageId;
  int? CountryId;
  String? Language;
  String? Langconvert;
  bool? isActive;
  bool? isSelected = false;

  LanguageResponseModelDataLangListData(
      {this.languageId, this.CountryId, this.Language, this.isActive, this.Langconvert, this.isSelected = false});

  LanguageResponseModelDataLangListData.fromJson(Map<String, dynamic> json) {
    languageId = asInt(json['languageId']);
    CountryId = asIntFrom(json, ['Country_Id', 'countryId']);
    Language = asString(json['Language']);
    Langconvert = asString(json['Langconvert']);
    isActive = asBool(json['isActive']);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['languageId'] = languageId;
    data['Country_Id'] = CountryId;
    data['Language'] = Language;
    data['isActive'] = isActive;
    return data;
  }
}

class LanguageResponseModelData with JsonSafeParser {
/*
{
  "status": 200,
  "langListData": [
    {
      "languageId": 252,
      "Country_Id": 104,
      "Language": "English",
      "isActive": true
    }
  ]
}
*/

  int? status;
  List<LanguageResponseModelDataLangListData?>? langListData;
  List<DataError?>? error;

  LanguageResponseModelData({this.status, this.langListData, this.error});

  LanguageResponseModelData.fromJson(Map<String, dynamic> json) {
    status = asIntFrom(json, ['status', 'Status']);
    if (json['langListData'] != null) {
      langListData = asListOfMaps(json['langListData'])
          .map(LanguageResponseModelDataLangListData.fromJson)
          .toList();
    }
    if (json['error'] != null) {
      error = asListOfMaps(json['error']).map(DataError.fromJson).toList();
    }
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (langListData != null) {
      final v = langListData;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['langListData'] = arr0;
    }
    return data;
  }
}

class LanguageResponseModel with JsonSafeParser {
/*
{
  "data": {
    "status": 200,
    "langListData": [
      {
        "languageId": 252,
        "Country_Id": 104,
        "Language": "English",
        "isActive": true
      }
    ]
  }
}
*/

  LanguageResponseModelData? data;

  LanguageResponseModel({
    this.data,
  });

  LanguageResponseModel.fromJson(Map<String, dynamic> json) {
    final dataMap = asMapOrNull(json['data']);
    data = dataMap != null
        ? LanguageResponseModelData.fromJson(dataMap)
        : null;
  }

  Map<String, dynamic> toJson() {
    final res = <String, dynamic>{};
    if (data != null) {
      res['data'] = data!.toJson();
    }
    return res;
  }
}
