// class LanguageModel {
//   final String? title;
//   final String? subTitle;
//   bool? isSelected;
//   final String? image;
//   final String? languageCode;
//   final String? countryCode;

//   LanguageModel(
//       {this.title,
//       this.countryCode,
//       this.subTitle,
//       this.isSelected = false,
//       this.image,
//       this.languageCode});
// }

import '../../login/model/client_model.dart';

class Language {
  final String? langCode;

  // final String? countryCode;

  Language({required this.langCode});
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LanguageResponseModelDataLangListData {
/*
{
  "languageId": 252,
  "Country_Id": 104,
  "Language": "English",
  "isActive": true
} 
*/

  int? languageId;
  int? CountryId;
  String? Language;
  String? Langconvert;
  bool? isActive;
  bool? isSelected = false;

  LanguageResponseModelDataLangListData(
      {this.languageId, this.CountryId, this.Language, this.isActive, this.Langconvert, this.isSelected = false});

  LanguageResponseModelDataLangListData.fromJson(Map<String, dynamic> json) {
    languageId = json['languageId']?.toInt();
    CountryId = json['Country_Id']?.toInt();
    Language = json['Language']?.toString();
    Langconvert = json['Langconvert'];

    isActive = json['isActive'];
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['languageId'] = languageId;
    data['Country_Id'] = CountryId;
    data['Language'] = Language;
    data['isActive'] = isActive;
    return data;
  }
}

class LanguageResponseModelData {
/*
{
  "status": 200,
  "langListData": [
    {
      "languageId": 252,
      "Country_Id": 104,
      "Language": "English",
      "isActive": true
    }
  ]
}
*/

  int? status;
  List<LanguageResponseModelDataLangListData?>? langListData;
  List<DataError?>? error;

  LanguageResponseModelData({this.status, this.langListData, this.error});

  LanguageResponseModelData.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    if (json['langListData'] != null) {
      final v = json['langListData'];
      print("Input data: $v");
      final arr0 = <LanguageResponseModelDataLangListData>[];

      if (v.isNotEmpty) {
        v.forEach((item) {
          try {
            arr0.add(LanguageResponseModelDataLangListData.fromJson(item));
          } catch (e) {
            print("Input Error converting item: $item, Error: $e");
          }
        });
      } else {
        print("Input data is empty!");
      }

      langListData = arr0;
    }
    if (json['error'] != null) {
      final v = json['error'];
      final arr0 = <DataError>[];
      v.forEach((v) {
        arr0.add(DataError.fromJson(v));
      });
      error = arr0;
    }
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (langListData != null) {
      final v = langListData;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['langListData'] = arr0;
    }
    return data;
  }
}

class LanguageResponseModel {
/*
{
  "data": {
    "status": 200,
    "langListData": [
      {
        "languageId": 252,
        "Country_Id": 104,
        "Language": "English",
        "isActive": true
      }
    ]
  }
}
*/

  LanguageResponseModelData? data;

  LanguageResponseModel({
    this.data,
  });

  LanguageResponseModel.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null) ? LanguageResponseModelData.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final res = <String, dynamic>{};
    if (data != null) {
      res['data'] = data!.toJson();
    }
    return res;
  }
}
