import '../../login/model/client_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class VideoPlayBackResponseModelDataPlaybackvideo {
/*
{
  "vehicleid": 14,
  "Purl": "https://uyenotestlivevideo.infotracktelematics.com:9965/vss/apiPage/ReplayVideo.html?token==21232f297a57a5a743894a0e4a801fc3&deviceId=62071&chs=1_2_3_4_5_6_7_8&st=20230504023500&et=20230504024000&wnum=8&panel=1&speed=1&buffer=2000",
  "startdate": "20230504023500",
  "enddate": "20230504024000"
} 
*/

  int? vehicleid;
  String? Purl;
  String? startdate;
  String? enddate;

  VideoPlayBackResponseModelDataPlaybackvideo({
    this.vehicleid,
    this.Purl,
    this.startdate,
    this.enddate,
  });
  VideoPlayBackResponseModelDataPlaybackvideo.fromJson(
      Map<String, dynamic> json) {
    vehicleid = json['vehicleid']?.toInt();
    Purl = json['Purl']?.toString();
    startdate = json['startdate']?.toString();
    enddate = json['enddate']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['vehicleid'] = vehicleid;
    data['Purl'] = Purl;
    data['startdate'] = startdate;
    data['enddate'] = enddate;
    return data;
  }
}

class VideoPlayBackResponseModelData {
/*
{
  "status": 200,
  "playbackvideo": [
    {
      "vehicleid": 14,
      "Purl": "https://uyenotestlivevideo.infotracktelematics.com:9965/vss/apiPage/ReplayVideo.html?token==21232f297a57a5a743894a0e4a801fc3&deviceId=62071&chs=1_2_3_4_5_6_7_8&st=20230504023500&et=20230504024000&wnum=8&panel=1&speed=1&buffer=2000",
      "startdate": "20230504023500",
      "enddate": "20230504024000"
    }
  ]
} 
*/

  int? status;
  List<VideoPlayBackResponseModelDataPlaybackvideo?>? playbackvideo;
  List<DataError?>? error;

  VideoPlayBackResponseModelData({
    this.status,
    this.playbackvideo,
  });
  VideoPlayBackResponseModelData.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    if (json['playbackvideo'] != null) {
      final v = json['playbackvideo'];
      final arr0 = <VideoPlayBackResponseModelDataPlaybackvideo>[];
      v.forEach((v) {
        arr0.add(VideoPlayBackResponseModelDataPlaybackvideo.fromJson(v));
      });
      playbackvideo = arr0;
    }
    if (json['error'] != null) {
      final v = json['error'];
      final arr0 = <DataError>[];
      v.forEach((v) {
        arr0.add(DataError.fromJson(v));
      });
      error = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (playbackvideo != null) {
      final v = playbackvideo;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['playbackvideo'] = arr0;
    }
    return data;
  }
}

class VideoPlayBackResponseModel {
/*
{
  "data": {
    "status": 200,
    "playbackvideo": [
      {
        "vehicleid": 14,
        "Purl": "https://uyenotestlivevideo.infotracktelematics.com:9965/vss/apiPage/ReplayVideo.html?token==21232f297a57a5a743894a0e4a801fc3&deviceId=62071&chs=1_2_3_4_5_6_7_8&st=20230504023500&et=20230504024000&wnum=8&panel=1&speed=1&buffer=2000",
        "startdate": "20230504023500",
        "enddate": "20230504024000"
      }
    ]
  }
} 
*/

  VideoPlayBackResponseModelData? data;

  VideoPlayBackResponseModel({
    this.data,
  });
  VideoPlayBackResponseModel.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? VideoPlayBackResponseModelData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data!.toJson();
    return data;
  }
}
