import '../../../utils/json_safe_parser.dart';
import '../../login/model/client_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class VideoPlayBackResponseModelDataPlaybackvideo with JsonSafeParser {
/*
{
  "vehicleid": 14,
  "Purl": "https://uyenotestlivevideo.infotracktelematics.com:9965/vss/apiPage/ReplayVideo.html?token==21232f297a57a5a743894a0e4a801fc3&deviceId=62071&chs=1_2_3_4_5_6_7_8&st=20230504023500&et=20230504024000&wnum=8&panel=1&speed=1&buffer=2000",
  "startdate": "20230504023500",
  "enddate": "20230504024000"
} 
*/

  int? vehicleid;
  String? Purl;
  String? startdate;
  String? enddate;

  VideoPlayBackResponseModelDataPlaybackvideo({
    this.vehicleid,
    this.Purl,
    this.startdate,
    this.enddate,
  });
  VideoPlayBackResponseModelDataPlaybackvideo.fromJson(
      Map<String, dynamic> json) {
    vehicleid = asIntFrom(json, ['vehicleid', 'vehicleId']);
    Purl = asStringFrom(json, ['Purl', 'purl', 'pUrl', 'URL', 'url']);
    startdate = asStringFrom(json, ['startdate', 'startDate']);
    enddate = asStringFrom(json, ['enddate', 'endDate']);
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['vehicleid'] = vehicleid;
    data['Purl'] = Purl;
    data['startdate'] = startdate;
    data['enddate'] = enddate;
    return data;
  }
}

class VideoPlayBackResponseModelData with JsonSafeParser {
/*
{
  "status": 200,
  "playbackvideo": [
    {
      "vehicleid": 14,
      "Purl": "https://uyenotestlivevideo.infotracktelematics.com:9965/vss/apiPage/ReplayVideo.html?token==21232f297a57a5a743894a0e4a801fc3&deviceId=62071&chs=1_2_3_4_5_6_7_8&st=20230504023500&et=20230504024000&wnum=8&panel=1&speed=1&buffer=2000",
      "startdate": "20230504023500",
      "enddate": "20230504024000"
    }
  ]
} 
*/

  int? status;
  String? message;
  List<VideoPlayBackResponseModelDataPlaybackvideo?>? playbackvideo;
  List<DataError?>? error;

  VideoPlayBackResponseModelData({
    this.status,
    this.message,
    this.playbackvideo,
  });
  VideoPlayBackResponseModelData.fromJson(Map<String, dynamic> json) {
    status = asIntFrom(json, ['status', 'Status']);
    message = asStringFrom(json, ['message', 'Message']);
    playbackvideo = asListOfMaps(firstValue(json, [
      'playbackvideo',
      'playbackVideo',
      'PlaybackVideo',
    ]))
        .map(VideoPlayBackResponseModelDataPlaybackvideo.fromJson)
        .toList();
    error = asListOfMaps(firstValue(json, ['error', 'Error']))
        .map(DataError.fromJson)
        .toList();
  }

  bool get isSuccess => status == 1 || status == 200;

  VideoPlayBackResponseModelDataPlaybackvideo? get firstPlayback {
    for (final item in playbackvideo ?? const []) {
      final url = item?.Purl?.trim();
      if (item != null && url != null && url.isNotEmpty) return item;
    }
    return null;
  }

  String? get playbackUrl {
    final url = firstPlayback?.Purl?.trim();
    if (url == null || url.isEmpty) return null;
    return url;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (playbackvideo != null) {
      final v = playbackvideo;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['playbackvideo'] = arr0;
    }
    return data;
  }
}

class VideoPlayBackResponseModel with JsonSafeParser {
/*
{
  "data": {
    "status": 200,
    "playbackvideo": [
      {
        "vehicleid": 14,
        "Purl": "https://uyenotestlivevideo.infotracktelematics.com:9965/vss/apiPage/ReplayVideo.html?token==21232f297a57a5a743894a0e4a801fc3&deviceId=62071&chs=1_2_3_4_5_6_7_8&st=20230504023500&et=20230504024000&wnum=8&panel=1&speed=1&buffer=2000",
        "startdate": "20230504023500",
        "enddate": "20230504024000"
      }
    ]
  }
} 
*/

  VideoPlayBackResponseModelData? data;

  VideoPlayBackResponseModel({
    this.data,
  });
  VideoPlayBackResponseModel.fromJson(Map<String, dynamic> json) {
    final nested = asMapOrNull(firstValue(json, ['data', 'Data']));
    if (nested != null &&
        (nested.containsKey('playbackvideo') ||
            nested.containsKey('playbackVideo') ||
            nested.containsKey('status') ||
            nested.containsKey('Status'))) {
      data = VideoPlayBackResponseModelData.fromJson(nested);
      return;
    }
    data = VideoPlayBackResponseModelData.fromJson(json);
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data!.toJson();
    return data;
  }
}
