// ignore_for_file: non_constant_identifier_names

import '../../../utils/json_safe_parser.dart';
import '../../login/model/client_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AdsResponseModelDataAdvertise with JsonSafeParser {
/*
{
  "ClientAdvertiseID": 13,
  "ClientID": 1,
  "ClientAdvertiseUrl": "https://muserstaging.infotracktelematics.com:7010/images/image_1686214926482.png",
  "CreateDate": "2023-06-08T18:02:00.000Z",
  "ValidDate": "2023-06-17T15:00:00.000Z"
} 
*/

  int? ClientAdvertiseID;
  int? ClientID;
  String? ClientAdvertiseUrl;
  String? CreateDate;
  String? ValidDate;

  AdsResponseModelDataAdvertise({
    this.ClientAdvertiseID,
    this.ClientID,
    this.ClientAdvertiseUrl,
    this.CreateDate,
    this.ValidDate,
  });
  AdsResponseModelDataAdvertise.fromJson(Map<String, dynamic> json) {
    ClientAdvertiseID = asInt(json['ClientAdvertiseID']);
    ClientID = asInt(json['ClientID']);
    ClientAdvertiseUrl = asString(json['ClientAdvertiseUrl']);
    CreateDate = asString(json['CreateDate']);
    ValidDate = asString(json['ValidDate']);
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ClientAdvertiseID'] = ClientAdvertiseID;
    data['ClientID'] = ClientID;
    data['ClientAdvertiseUrl'] = ClientAdvertiseUrl;
    data['CreateDate'] = CreateDate;
    data['ValidDate'] = ValidDate;
    return data;
  }
}

class AdsResponseModelData with JsonSafeParser {
/*
{
  "status": 200,
  "advertise": [
    {
      "ClientAdvertiseID": 13,
      "ClientID": 1,
      "ClientAdvertiseUrl": "https://muserstaging.infotracktelematics.com:7010/images/image_1686214926482.png",
      "CreateDate": "2023-06-08T18:02:00.000Z",
      "ValidDate": "2023-06-17T15:00:00.000Z"
    }
  ]
} 
*/

  int? status;
  List<AdsResponseModelDataAdvertise?>? advertise;
  List<DataError?>? error;

  AdsResponseModelData({
    this.status,
    this.advertise,
  });
  AdsResponseModelData.fromJson(Map<String, dynamic> json) {
    status = asIntFrom(json, ['status', 'Status']);
    if (json['advertise'] != null) {
      advertise = asListOfMaps(json['advertise'])
          .map(AdsResponseModelDataAdvertise.fromJson)
          .toList();
    }
    if (json['error'] != null) {
      error = asListOfMaps(json['error']).map(DataError.fromJson).toList();
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (advertise != null) {
      final v = advertise;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['advertise'] = arr0;
    }

    return data;
  }
}

class AdsResponseModel with JsonSafeParser {
/*
{
  "data": {
    "status": 200,
    "advertise": [
      {
        "ClientAdvertiseID": 13,
        "ClientID": 1,
        "ClientAdvertiseUrl": "https://muserstaging.infotracktelematics.com:7010/images/image_1686214926482.png",
        "CreateDate": "2023-06-08T18:02:00.000Z",
        "ValidDate": "2023-06-17T15:00:00.000Z"
      }
    ]
  }
} 
*/

  AdsResponseModelData? data;

  AdsResponseModel({
    this.data,
  });
  AdsResponseModel.fromJson(Map<String, dynamic> json) {
    final dataMap = asMapOrNull(json['data']);
    data = dataMap != null ? AdsResponseModelData.fromJson(dataMap) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data!.toJson();
    return data;
  }
}
