// ignore_for_file: non_constant_identifier_names

import '../../login/model/client_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AdsResponseModelDataAdvertise {
/*
{
  "ClientAdvertiseID": 13,
  "ClientID": 1,
  "ClientAdvertiseUrl": "https://muserstaging.infotracktelematics.com:7010/images/image_1686214926482.png",
  "CreateDate": "2023-06-08T18:02:00.000Z",
  "ValidDate": "2023-06-17T15:00:00.000Z"
} 
*/

  int? ClientAdvertiseID;
  int? ClientID;
  String? ClientAdvertiseUrl;
  String? CreateDate;
  String? ValidDate;

  AdsResponseModelDataAdvertise({
    this.ClientAdvertiseID,
    this.ClientID,
    this.ClientAdvertiseUrl,
    this.CreateDate,
    this.ValidDate,
  });
  AdsResponseModelDataAdvertise.fromJson(Map<String, dynamic> json) {
    ClientAdvertiseID = json['ClientAdvertiseID']?.toInt();
    ClientID = json['ClientID']?.toInt();
    ClientAdvertiseUrl = json['ClientAdvertiseUrl']?.toString();
    CreateDate = json['CreateDate']?.toString();
    ValidDate = json['ValidDate']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ClientAdvertiseID'] = ClientAdvertiseID;
    data['ClientID'] = ClientID;
    data['ClientAdvertiseUrl'] = ClientAdvertiseUrl;
    data['CreateDate'] = CreateDate;
    data['ValidDate'] = ValidDate;
    return data;
  }
}

class AdsResponseModelData {
/*
{
  "status": 200,
  "advertise": [
    {
      "ClientAdvertiseID": 13,
      "ClientID": 1,
      "ClientAdvertiseUrl": "https://muserstaging.infotracktelematics.com:7010/images/image_1686214926482.png",
      "CreateDate": "2023-06-08T18:02:00.000Z",
      "ValidDate": "2023-06-17T15:00:00.000Z"
    }
  ]
} 
*/

  int? status;
  List<AdsResponseModelDataAdvertise?>? advertise;
  List<DataError?>? error;

  AdsResponseModelData({
    this.status,
    this.advertise,
  });
  AdsResponseModelData.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    if (json['advertise'] != null) {
      final v = json['advertise'];
      final arr0 = <AdsResponseModelDataAdvertise>[];
      v.forEach((v) {
        arr0.add(AdsResponseModelDataAdvertise.fromJson(v));
      });
      advertise = arr0;
    }
    if (json['error'] != null) {
      final v = json['error'];
      final arr0 = <DataError>[];
      v.forEach((v) {
        arr0.add(DataError.fromJson(v));
      });
      error = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (advertise != null) {
      final v = advertise;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['advertise'] = arr0;
    }

    return data;
  }
}

class AdsResponseModel {
/*
{
  "data": {
    "status": 200,
    "advertise": [
      {
        "ClientAdvertiseID": 13,
        "ClientID": 1,
        "ClientAdvertiseUrl": "https://muserstaging.infotracktelematics.com:7010/images/image_1686214926482.png",
        "CreateDate": "2023-06-08T18:02:00.000Z",
        "ValidDate": "2023-06-17T15:00:00.000Z"
      }
    ]
  }
} 
*/

  AdsResponseModelData? data;

  AdsResponseModel({
    this.data,
  });
  AdsResponseModel.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? AdsResponseModelData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data!.toJson();
    return data;
  }
}
