import 'package:flutter/material.dart';

import '../../../utils/json_safe_parser.dart';
import '../../login/model/client_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DashboardResponseModelDataPinvehicle with JsonSafeParser {
/*
{
  "cardType": "D3",
  "id": 1,
  "VehicleId": 34,
  "VehicleNo": "72070",
  "DriverName": null,
  "TrackingTime": "2023-04-24 19:42:04",
  "Location": "〒870-0823 大分県大分市東大道２丁目２−１６",
  "speed": 0,
  "ignition": "On",
  "odometer": 1367.33,
  "Idleduration": 28675,
  "Status": "Idle",
  "DelayEnable": 90,
  "LiveUrl": "https://uyenotestlivevideo.infotracktelematics.com:9965/vss/apiPage/RealVideo.html?token==21232f297a57a5a743894a0e4a801fc3&deviceId=72070&chs=1_2_3_4&stream=0&wnum=4&panel=1",
  "Mapit": "33.2293,131.603",
  "Cid": 3
} 
*/

  String? cardType;
  int? id;
  int? VehicleId;
  String? VehicleNo;
  String? DriverName;
  String? TrackingTime;
  String? Location;
  int? speed;
  String? ignition;
  double? odometer;
  int? Idleduration;
  String? Status;
  int? DelayEnable;
  String? LiveUrl;
  String? Mapit;
  int? Cid;
  bool isPin=true;

  DashboardResponseModelDataPinvehicle(
      {this.cardType,
      this.id,
      this.VehicleId,
      this.VehicleNo,
      this.DriverName,
      this.TrackingTime,
      this.Location,
      this.speed,
      this.ignition,
      this.odometer,
      this.Idleduration,
      this.Status,
      this.DelayEnable,
      this.LiveUrl,
      this.Mapit,
      this.Cid,
      this.isPin = true});
  DashboardResponseModelDataPinvehicle.fromJson(Map<String, dynamic> json) {
    cardType = asString(json['cardType']);
    id = asInt(json['id']);
    VehicleId = asIntFrom(json, ['VehicleId', 'vehicleId']);
    VehicleNo = asStringFrom(json, ['VehicleNo', 'vehicleNo']);
    DriverName = asStringFrom(json, ['DriverName', 'driverName']);
    TrackingTime = asStringFrom(json, ['TrackingTime', 'trackingTime']);
    Location = asStringFrom(json, ['Location', 'location']);
    speed = asInt(json['speed']);
    ignition = asString(json['ignition']);
    odometer = asDouble(json['odometer']);
    Idleduration =
        asIntFrom(json, ['Idleduration', 'idleduration', 'idleDuration']);
    Status = asStringFrom(json, ['Status', 'status']);
    DelayEnable = asIntFrom(json, ['DelayEnable', 'delayEnable']);
    LiveUrl = asStringFrom(json, ['LiveUrl', 'liveUrl']);
    Mapit = asStringFrom(json, ['Mapit', 'mapit', 'mapIt']);
    Cid = asIntFrom(json, ['Cid', 'cid']);
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['cardType'] = cardType;
    data['id'] = id;
    data['VehicleId'] = VehicleId;
    data['VehicleNo'] = VehicleNo;
    data['DriverName'] = DriverName;
    data['TrackingTime'] = TrackingTime;
    data['Location'] = Location;
    data['speed'] = speed;
    data['ignition'] = ignition;
    data['odometer'] = odometer;
    data['Idleduration'] = Idleduration;
    data['Status'] = Status;
    data['DelayEnable'] = DelayEnable;
    data['LiveUrl'] = LiveUrl;
    data['Mapit'] = Mapit;
    data['Cid'] = Cid;
    return data;
  }
}

class DashboardResponseModelDataStatusCount with JsonSafeParser {
/*
{
  "cardType": "D2",
  "id": 1,
  "AlertCount": 18,
  "AlertTypeID": 9,
  "cid": 2,
  "AlertType": "Over Speed"
} 
*/

  String? cardType;
  int? id;
  int? AlertCount;
  int? AlertTypeID;
  int? cid;
  String? AlertType;

  DashboardResponseModelDataStatusCount({
    this.cardType,
    this.id,
    this.AlertCount,
    this.AlertTypeID,
    this.cid,
    this.AlertType,
  });
  DashboardResponseModelDataStatusCount.fromJson(Map<String, dynamic> json) {
    cardType = asString(json['cardType']);
    id = asInt(json['id']);
    AlertCount = asIntFrom(json, ['AlertCount', 'alertCount']);
    AlertTypeID = asIntFrom(json, ['AlertTypeID', 'alertTypeID', 'alertTypeId']);
    cid = asIntFrom(json, ['cid', 'Cid']);
    AlertType = asStringFrom(json, ['AlertType', 'alertType']);
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['cardType'] = cardType;
    data['id'] = id;
    data['AlertCount'] = AlertCount;
    data['AlertTypeID'] = AlertTypeID;
    data['cid'] = cid;
    data['AlertType'] = AlertType;
    return data;
  }
}

class DashboardResponseModelDataVehicleStatus with JsonSafeParser {
/*
{
  "cardType": "D1",
  "status": "Inactive",
  "Value": 8,
  "StatusID": 4,
  "Cid": 1
} 
*/

  String? cardType;
  String? status;
  int? Value;
  int? StatusID;
  int? Cid;
  int? SequenceId;
  Color? color;

  DashboardResponseModelDataVehicleStatus({
    this.cardType,
    this.status,
    this.Value,
    this.StatusID,
    this.Cid,
    this.SequenceId,
    this.color,
  });
  DashboardResponseModelDataVehicleStatus.fromJson(Map<String, dynamic> json) {
    cardType = asString(json['cardType']);
    status = asString(json['status']);
    Value = asIntFrom(json, ['Value', 'value']);
    StatusID = asIntFrom(json, ['StatusID', 'statusId', 'StatusId']);
    Cid = asIntFrom(json, ['Cid', 'cid']);
    SequenceId = asIntFrom(json, ['SequenceId', 'sequenceId']);
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['cardType'] = cardType;
    data['status'] = status;
    data['Value'] = Value;
    data['StatusID'] = StatusID;
    data['Cid'] = Cid;
    data['SequenceId'] = SequenceId;
    return data;
  }
}

class DashboardResponseModelData with JsonSafeParser {
/*
{
  "status": 200,
  "VehicleStatus": [
    {
      "cardType": "D1",
      "status": "Inactive",
      "Value": 8,
      "StatusID": 4,
      "Cid": 1
    }
  ],
  "StatusCount": [
    {
      "cardType": "D2",
      "id": 1,
      "AlertCount": 18,
      "AlertTypeID": 9,
      "cid": 2,
      "AlertType": "Over Speed"
    }
  ],
  "Pinvehicle": [
    {
      "cardType": "D2",
      "id": 4,
      "AlertCount": 3,
      "AlertTypeID": 141,
      "cid": 2,
      "AlertType": "tilt end"
    }
  ]
} 
*/

  int? status;
  List<DashboardResponseModelDataVehicleStatus?>? VehicleStatus;
  List<DashboardResponseModelDataStatusCount?>? StatusCount;
  List<DashboardResponseModelDataPinvehicle?>? Pinvehicle;
  List<DataError?>? error;

  DashboardResponseModelData(
      {this.status,
      this.VehicleStatus,
      this.StatusCount,
      this.Pinvehicle,
      this.error});
  DashboardResponseModelData.fromJson(Map<String, dynamic> json) {
    status = asIntFrom(json, ['status', 'Status']);
    if (json['VehicleStatus'] != null || json['vehicleStatus'] != null) {
      VehicleStatus = asListOfMaps(
              json['VehicleStatus'] ?? json['vehicleStatus'])
          .map(DashboardResponseModelDataVehicleStatus.fromJson)
          .toList();
    }
    if (json['StatusCount'] != null || json['statusCount'] != null) {
      StatusCount = asListOfMaps(json['StatusCount'] ?? json['statusCount'])
          .map(DashboardResponseModelDataStatusCount.fromJson)
          .toList();
    }
    if (json['Pinvehicle'] != null || json['pinvehicle'] != null) {
      Pinvehicle = asListOfMaps(json['Pinvehicle'] ?? json['pinvehicle'])
          .map(DashboardResponseModelDataPinvehicle.fromJson)
          .toList();
    }
    if (json['error'] != null) {
      error = asListOfMaps(json['error']).map(DataError.fromJson).toList();
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (VehicleStatus != null) {
      final v = VehicleStatus;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['VehicleStatus'] = arr0;
    }
    if (StatusCount != null) {
      final v = StatusCount;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['StatusCount'] = arr0;
    }
    // if (Pinvehicle != null) {
    //   final v = Pinvehicle;
    //   final arr0 = [];
    //   for (var v in v!) {
    //     arr0.add(v!.toJson());
    //   }
    //   data['Pinvehicle'] = arr0;
    // }
    return data;
  }
}

class DashboardResponseModel with JsonSafeParser {
/*
{
  "data": {
    "status": 200,
    "VehicleStatus": [
      {
        "cardType": "D1",
        "status": "Inactive",
        "Value": 8,
        "StatusID": 4,
        "Cid": 1
      }
    ],
    "StatusCount": [
      {
        "cardType": "D2",
        "id": 1,
        "AlertCount": 18,
        "AlertTypeID": 9,
        "cid": 2,
        "AlertType": "Over Speed"
      }
    ],
    "Pinvehicle": [
      {
        "cardType": "D2",
        "id": 4,
        "AlertCount": 3,
        "AlertTypeID": 141,
        "cid": 2,
        "AlertType": "tilt end"
      }
    ]
  }
} 
*/

  DashboardResponseModelData? data;

  DashboardResponseModel({
    this.data,
  });
  DashboardResponseModel.fromJson(Map<String, dynamic> json) {
    final dataMap = asMapOrNull(json['data']);
    data = dataMap != null
        ? DashboardResponseModelData.fromJson(dataMap)
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data!.toJson();
    return data;
  }
}
