import 'package:flutter/material.dart';

import '../../login/model/client_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DashboardResponseModelDataPinvehicle {
/*
{
  "cardType": "D3",
  "id": 1,
  "VehicleId": 34,
  "VehicleNo": "72070",
  "DriverName": null,
  "TrackingTime": "2023-04-24 19:42:04",
  "Location": "〒870-0823 大分県大分市東大道２丁目２−１６",
  "speed": 0,
  "ignition": "On",
  "odometer": 1367.33,
  "Idleduration": 28675,
  "Status": "Idle",
  "DelayEnable": 90,
  "LiveUrl": "https://uyenotestlivevideo.infotracktelematics.com:9965/vss/apiPage/RealVideo.html?token==21232f297a57a5a743894a0e4a801fc3&deviceId=72070&chs=1_2_3_4&stream=0&wnum=4&panel=1",
  "Mapit": "33.2293,131.603",
  "Cid": 3
} 
*/

  String? cardType;
  int? id;
  int? VehicleId;
  String? VehicleNo;
  String? DriverName;
  String? TrackingTime;
  String? Location;
  int? speed;
  String? ignition;
  double? odometer;
  int? Idleduration;
  String? Status;
  int? DelayEnable;
  String? LiveUrl;
  String? Mapit;
  int? Cid;
  bool isPin=true;

  DashboardResponseModelDataPinvehicle(
      {this.cardType,
      this.id,
      this.VehicleId,
      this.VehicleNo,
      this.DriverName,
      this.TrackingTime,
      this.Location,
      this.speed,
      this.ignition,
      this.odometer,
      this.Idleduration,
      this.Status,
      this.DelayEnable,
      this.LiveUrl,
      this.Mapit,
      this.Cid,
      this.isPin = true});
  DashboardResponseModelDataPinvehicle.fromJson(Map<String, dynamic> json) {
    cardType = json['cardType']?.toString();
    id = json['id']?.toInt();
    VehicleId = json['VehicleId']?.toInt();
    VehicleNo = json['VehicleNo']?.toString();
    DriverName = json['DriverName']?.toString();
    TrackingTime = json['TrackingTime']?.toString();
    Location = json['Location']?.toString();
    speed = json['speed']?.toInt();
    ignition = json['ignition']?.toString();
    odometer = json['odometer']?.toDouble();
    Idleduration = json['Idleduration']?.toInt();
    Status = json['Status']?.toString();
    DelayEnable = json['DelayEnable']?.toInt();
    LiveUrl = json['LiveUrl']?.toString();
    Mapit = json['Mapit']?.toString();
    Cid = json['Cid']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['cardType'] = cardType;
    data['id'] = id;
    data['VehicleId'] = VehicleId;
    data['VehicleNo'] = VehicleNo;
    data['DriverName'] = DriverName;
    data['TrackingTime'] = TrackingTime;
    data['Location'] = Location;
    data['speed'] = speed;
    data['ignition'] = ignition;
    data['odometer'] = odometer;
    data['Idleduration'] = Idleduration;
    data['Status'] = Status;
    data['DelayEnable'] = DelayEnable;
    data['LiveUrl'] = LiveUrl;
    data['Mapit'] = Mapit;
    data['Cid'] = Cid;
    return data;
  }
}

class DashboardResponseModelDataStatusCount {
/*
{
  "cardType": "D2",
  "id": 1,
  "AlertCount": 18,
  "AlertTypeID": 9,
  "cid": 2,
  "AlertType": "Over Speed"
} 
*/

  String? cardType;
  int? id;
  int? AlertCount;
  int? AlertTypeID;
  int? cid;
  String? AlertType;

  DashboardResponseModelDataStatusCount({
    this.cardType,
    this.id,
    this.AlertCount,
    this.AlertTypeID,
    this.cid,
    this.AlertType,
  });
  DashboardResponseModelDataStatusCount.fromJson(Map<String, dynamic> json) {
    cardType = json['cardType']?.toString();
    id = json['id']?.toInt();
    AlertCount = json['AlertCount']?.toInt();
    AlertTypeID = json['AlertTypeID']?.toInt();
    cid = json['cid']?.toInt();
    AlertType = json['AlertType']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['cardType'] = cardType;
    data['id'] = id;
    data['AlertCount'] = AlertCount;
    data['AlertTypeID'] = AlertTypeID;
    data['cid'] = cid;
    data['AlertType'] = AlertType;
    return data;
  }
}

class DashboardResponseModelDataVehicleStatus {
/*
{
  "cardType": "D1",
  "status": "Inactive",
  "Value": 8,
  "StatusID": 4,
  "Cid": 1
} 
*/

  String? cardType;
  String? status;
  int? Value;
  int? StatusID;
  int? Cid;
  int? SequenceId;
  Color? color;

  DashboardResponseModelDataVehicleStatus({
    this.cardType,
    this.status,
    this.Value,
    this.StatusID,
    this.Cid,
    this.SequenceId,
    this.color,
  });
  DashboardResponseModelDataVehicleStatus.fromJson(Map<String, dynamic> json) {
    cardType = json['cardType']?.toString();
    status = json['status']?.toString();
    Value = json['Value']?.toInt();
    StatusID = json['StatusID']?.toInt();
    Cid = json['Cid']?.toInt();
    SequenceId = json['SequenceId']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['cardType'] = cardType;
    data['status'] = status;
    data['Value'] = Value;
    data['StatusID'] = StatusID;
    data['Cid'] = Cid;
    data['SequenceId'] = SequenceId;
    return data;
  }
}

class DashboardResponseModelData {
/*
{
  "status": 200,
  "VehicleStatus": [
    {
      "cardType": "D1",
      "status": "Inactive",
      "Value": 8,
      "StatusID": 4,
      "Cid": 1
    }
  ],
  "StatusCount": [
    {
      "cardType": "D2",
      "id": 1,
      "AlertCount": 18,
      "AlertTypeID": 9,
      "cid": 2,
      "AlertType": "Over Speed"
    }
  ],
  "Pinvehicle": [
    {
      "cardType": "D2",
      "id": 4,
      "AlertCount": 3,
      "AlertTypeID": 141,
      "cid": 2,
      "AlertType": "tilt end"
    }
  ]
} 
*/

  int? status;
  List<DashboardResponseModelDataVehicleStatus?>? VehicleStatus;
  List<DashboardResponseModelDataStatusCount?>? StatusCount;
  List<DashboardResponseModelDataPinvehicle?>? Pinvehicle;
  List<DataError?>? error;

  DashboardResponseModelData(
      {this.status,
      this.VehicleStatus,
      this.StatusCount,
      this.Pinvehicle,
      this.error});
  DashboardResponseModelData.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    if (json['VehicleStatus'] != null) {
      final v = json['VehicleStatus'];
      final arr0 = <DashboardResponseModelDataVehicleStatus>[];
      v.forEach((v) {
        arr0.add(DashboardResponseModelDataVehicleStatus.fromJson(v));
      });
      VehicleStatus = arr0;
    }
    if (json['StatusCount'] != null) {
      final v = json['StatusCount'];
      final arr0 = <DashboardResponseModelDataStatusCount>[];
      v.forEach((v) {
        arr0.add(DashboardResponseModelDataStatusCount.fromJson(v));
      });
      StatusCount = arr0;
    }
    if (json['Pinvehicle'] != null) {
      final v = json['Pinvehicle'];
      final arr0 = <DashboardResponseModelDataPinvehicle>[];
      v.forEach((v) {
        arr0.add(DashboardResponseModelDataPinvehicle.fromJson(v));
      });
      Pinvehicle = arr0;
    }
    if (json['error'] != null) {
      final v = json['error'];
      final arr0 = <DataError>[];
      v.forEach((v) {
        arr0.add(DataError.fromJson(v));
      });
      error = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (VehicleStatus != null) {
      final v = VehicleStatus;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['VehicleStatus'] = arr0;
    }
    if (StatusCount != null) {
      final v = StatusCount;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['StatusCount'] = arr0;
    }
    // if (Pinvehicle != null) {
    //   final v = Pinvehicle;
    //   final arr0 = [];
    //   for (var v in v!) {
    //     arr0.add(v!.toJson());
    //   }
    //   data['Pinvehicle'] = arr0;
    // }
    return data;
  }
}

class DashboardResponseModel {
/*
{
  "data": {
    "status": 200,
    "VehicleStatus": [
      {
        "cardType": "D1",
        "status": "Inactive",
        "Value": 8,
        "StatusID": 4,
        "Cid": 1
      }
    ],
    "StatusCount": [
      {
        "cardType": "D2",
        "id": 1,
        "AlertCount": 18,
        "AlertTypeID": 9,
        "cid": 2,
        "AlertType": "Over Speed"
      }
    ],
    "Pinvehicle": [
      {
        "cardType": "D2",
        "id": 4,
        "AlertCount": 3,
        "AlertTypeID": 141,
        "cid": 2,
        "AlertType": "tilt end"
      }
    ]
  }
} 
*/

  DashboardResponseModelData? data;

  DashboardResponseModel({
    this.data,
  });
  DashboardResponseModel.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? DashboardResponseModelData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data!.toJson();
    return data;
  }
}
