///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AlertListRequestModel {
/*
{
  "UserId": 1,
  "AlertTypeId": 10,
  "pSize": 100,
  "PNo": 1,
   "vno": "",
    "alertdt": "2023-04-27 00:00:00",
} 
*/

  int? userId;
  int? alertTypeId;
  int? pSize;
  int? pNo;
  String? vno;
  // String? alertdt;
  String? fromDate;
  String? toDate;

  AlertListRequestModel(
      {this.userId,
      this.alertTypeId,
      this.pSize,
      this.pNo,
      // this.alertdt,
      required this.fromDate,
      required this.toDate,
      this.vno = ''});

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['UserId'] = userId;
    data['AlertTypeId'] = alertTypeId;
    data['pSize'] = pSize;
    data['PNo'] = pNo;
    data['fromdt'] = fromDate;
    data['todt'] = toDate;
    data['vno'] = vno;
    return data;
  }

  Map<String, dynamic> toSequelJson() {
    return {
      'userId': userId,
      'alertTypeId': alertTypeId,
      'pSize': pSize,
      'pNo': pNo,
      'fromdt': fromDate,
      'todt': toDate,
      'vno': vno ?? '',
    };
  }
}
