import '../../../utils/json_safe_parser.dart';
import '../../login/model/client_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
///
class AlertListResponseModelDataAlerttypes with JsonSafeParser {
/*
{
  "AlertTypeID": 9,
  "AlertType": "Over Speed"
}
*/

  int? AlertTypeID;
  String? AlertType;
  bool isSelected = false;

  AlertListResponseModelDataAlerttypes(
      {this.AlertTypeID, this.AlertType, this.isSelected = false});
  AlertListResponseModelDataAlerttypes.fromJson(Map<String, dynamic> json) {
    AlertTypeID = asIntFrom(json, ['AlertTypeID', 'alertTypeID', 'alertTypeId']);
    AlertType = asStringFrom(json, ['AlertType', 'alertType']);
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['AlertTypeID'] = AlertTypeID;
    data['AlertType'] = AlertType;
    return data;
  }
}

class AlertListResponseModelDataAlertcnt with JsonSafeParser {
/*
{
  "TotRec": 21
} 
*/

  int? TotRec;

  AlertListResponseModelDataAlertcnt({
    this.TotRec,
  });
  AlertListResponseModelDataAlertcnt.fromJson(Map<String, dynamic> json) {
    TotRec = asIntFrom(json, ['TotRec', 'totRec', 'recCnt', 'totalCount']);
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['TotRec'] = TotRec;
    return data;
  }
}

class AlertListResponseModelDataAlertdetails with JsonSafeParser {
/*
{
  "Id": 11,
  "AlertTypeID": 28,
  "AlertType": "yaccel end",
  "VehicleID": 190,
  "DriverID": null,
  "Alertdatetime": "2023-05-15 14:42:17",
  "Lat": 33.6992301940918,
  "Lon": 135.410842895508,
  "Location": " 和歌山県西牟婁郡上富田町朝来１９０１",
  "ignition": 0,
  "speed": 0,
  "direction": 0,
  "VehicleNo": "o6e2oohgkg",
  "Videofilepath": "1|RDovVnNzU2VydmljZS9odGRvY3MvdnNzRmlsZXMvYWxhcm1SZWNvcmQvMjAyM18wNV8xNS82MjA1NS9jaDAxXzIwMjMwNTE1XzE0NDIwN18xNDQyMjdfMDEyLmh3,2|RDovVnNzU2VydmljZS9odGRvY3MvdnNzRmlsZXMvYWxhcm1SZWNvcmQvMjAyM18wNV8xNS82MjA1NS9jaDAyXzIwMjMwNTE1XzE0NDIwN18xNDQyMjdfMDEyLmh3,3|RDovVnNzU2VydmljZS9odGRvY3MvdnNzRmlsZXMvYWxhcm1SZWNvcmQvMjAyM18wNV8xNS82MjA1NS9jaDAzXzIwMjMwNTE1XzE0NDIwN18xNDQyMjdfMDEyLmh3,4|RDovVnNzU2VydmljZS9odGRvY3MvdnNzRmlsZXMvYWxhcm1SZWNvcmQvMjAyM18wNV8xNS82MjA1NS9jaDA0XzIwMjMwNTE1XzE0NDIwN18xNDQyMjdfMDEyLmh3",
  "VFC": 4,
  "Status": "Alert",
  "Unitid": 6,
  "UnitNo": "62055",
  "drivername": "",
  "devicetype":""
} 
*/

  int? Id;
  int? AlertTypeID;
  String? AlertType;
  int? VehicleID;
  String? DriverID;
  String? Alertdatetime;
  double? Lat;
  double? Lon;
  String? Location;
  int? ignition;
  int? speed;
  int? direction;
  String? VehicleNo;
  String? Videofilepath;
  int? VFC;
  String? Status;
  int? Unitid;
  String? UnitNo;
  String? drivername;
  String? deviceType;

  AlertListResponseModelDataAlertdetails({
    this.Id,
    this.AlertTypeID,
    this.AlertType,
    this.VehicleID,
    this.DriverID,
    this.Alertdatetime,
    this.Lat,
    this.Lon,
    this.Location,
    this.ignition,
    this.speed,
    this.direction,
    this.VehicleNo,
    this.Videofilepath,
    this.VFC,
    this.Status,
    this.Unitid,
    this.UnitNo,
    this.drivername,
    this.deviceType
  });
  AlertListResponseModelDataAlertdetails.fromJson(Map<String, dynamic> json) {
    Id = asIntFrom(json, ['Id', 'id']);
    AlertTypeID = asIntFrom(json, ['AlertTypeID', 'alertTypeID', 'alertTypeId']);
    AlertType = asStringFrom(json, ['AlertType', 'alertType']);
    VehicleID = asIntFrom(json, ['VehicleID', 'vehicleId', 'VehicleId']);
    DriverID = asStringFrom(json, ['DriverID', 'driverId']);
    Alertdatetime = asStringFrom(json, [
      'Alertdatetime',
      'alertDatetime',
      'alertDateTime',
    ]);
    Lat = asDoubleOrNull(firstValue(json, [
      'Lat',
      'lat',
      'latitude',
      'Latitude',
    ]));
    Lon = asDoubleOrNull(firstValue(json, [
      'Lon',
      'lon',
      'lng',
      'longitude',
      'Longitude',
    ]));
    if (Lat == null || Lon == null) {
      final mapit =
          asStringOrNull(firstValue(json, ['Mapit', 'mapit', 'mapIt']));
      if (mapit != null && mapit.contains(',')) {
        final parts = mapit.split(',');
        Lat ??= double.tryParse(parts[0].trim());
        if (parts.length > 1) {
          Lon ??= double.tryParse(parts[1].trim());
        }
      }
    }
    Location = asStringFrom(json, ['Location', 'location']);
    ignition = asInt(json['ignition']);
    speed = asInt(json['speed']);
    direction = asInt(json['direction']);
    VehicleNo = asStringFrom(json, ['VehicleNo', 'vehicleNo']);
    Videofilepath = asStringFrom(json, ['Videofilepath', 'videoFilePath']);
    VFC = asIntFrom(json, ['VFC', 'vfc']);
    Status = asStringFrom(json, ['Status', 'status']);
    Unitid = asIntFrom(json, ['Unitid', 'unitId']);
    UnitNo = asStringFrom(json, ['UnitNo', 'unitNo']);
    drivername = asStringFrom(json, ['drivername', 'driverName']);
    deviceType = asStringFrom(json, ['devicetype', 'deviceType']);
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Id'] = Id;
    data['AlertTypeID'] = AlertTypeID;
    data['AlertType'] = AlertType;
    data['VehicleID'] = VehicleID;
    data['DriverID'] = DriverID;
    data['Alertdatetime'] = Alertdatetime;
    data['Lat'] = Lat;
    data['Lon'] = Lon;
    data['Location'] = Location;
    data['ignition'] = ignition;
    data['speed'] = speed;
    data['direction'] = direction;
    data['VehicleNo'] = VehicleNo;
    data['Videofilepath'] = Videofilepath;
    data['VFC'] = VFC;
    data['Status'] = Status;
    data['Unitid'] = Unitid;
    data['UnitNo'] = UnitNo;
    data['drivername'] = drivername;
    data['devicetype'] = deviceType;
    return data;
  }
}

class AlertListResponseModelData with JsonSafeParser {
/*
{
  "status": 200,
  "alertdetails": [
    {
      "Id": 11,
      "AlertTypeID": 28,
      "AlertType": "yaccel end",
      "VehicleID": 190,
      "DriverID": null,
      "Alertdatetime": "2023-05-15 14:42:17",
      "Lat": 33.6992301940918,
      "Lon": 135.410842895508,
      "Location": " 和歌山県西牟婁郡上富田町朝来１９０１",
      "ignition": 0,
      "speed": 0,
      "direction": 0,
      "VehicleNo": "o6e2oohgkg",
      "Videofilepath": "1|RDovVnNzU2VydmljZS9odGRvY3MvdnNzRmlsZXMvYWxhcm1SZWNvcmQvMjAyM18wNV8xNS82MjA1NS9jaDAxXzIwMjMwNTE1XzE0NDIwN18xNDQyMjdfMDEyLmh3,2|RDovVnNzU2VydmljZS9odGRvY3MvdnNzRmlsZXMvYWxhcm1SZWNvcmQvMjAyM18wNV8xNS82MjA1NS9jaDAyXzIwMjMwNTE1XzE0NDIwN18xNDQyMjdfMDEyLmh3,3|RDovVnNzU2VydmljZS9odGRvY3MvdnNzRmlsZXMvYWxhcm1SZWNvcmQvMjAyM18wNV8xNS82MjA1NS9jaDAzXzIwMjMwNTE1XzE0NDIwN18xNDQyMjdfMDEyLmh3,4|RDovVnNzU2VydmljZS9odGRvY3MvdnNzRmlsZXMvYWxhcm1SZWNvcmQvMjAyM18wNV8xNS82MjA1NS9jaDA0XzIwMjMwNTE1XzE0NDIwN18xNDQyMjdfMDEyLmh3",
      "VFC": 4,
      "Status": "Alert",
      "Unitid": 6,
      "UnitNo": "62055",
      "drivername": ""
    }
  ],
  "alertcnt": [
    {
      "TotRec": 21
    }
  ]
} 
*/

  int? status;
  List<AlertListResponseModelDataAlertdetails?>? alertdetails;
  List<AlertListResponseModelDataAlertcnt?>? alertcnt;
  List<DataError?>? error;
  List<AlertListResponseModelDataAlerttypes?>? alerttypes;

  AlertListResponseModelData(
      {this.status,
      this.alertdetails,
      this.alertcnt,
      this.alerttypes,
      this.error});
  AlertListResponseModelData.fromJson(Map<String, dynamic> json) {
    status = asIntFrom(json, ['status', 'Status']);
    final detailsRaw = asListOrNull(
        firstValue(json, ['alertdetails', 'alertDetails', 'alertList']));
    if (detailsRaw != null) {
      alertdetails = asListOfMaps(detailsRaw)
          .map(AlertListResponseModelDataAlertdetails.fromJson)
          .toList();
    }
    final countRaw = asListOrNull(
        firstValue(json, ['alertcnt', 'alertCnt', 'alertCount']));
    if (countRaw != null) {
      alertcnt = asListOfMaps(countRaw)
          .map(AlertListResponseModelDataAlertcnt.fromJson)
          .toList();
    } else if (alertdetails != null) {
      alertcnt = [
        AlertListResponseModelDataAlertcnt(TotRec: alertdetails!.length),
      ];
    }
    final typesRaw = asListOrNull(
        firstValue(json, ['alerttypes', 'alertTypes', 'alerttype']));
    if (typesRaw != null) {
      alerttypes = asListOfMaps(typesRaw)
          .map(AlertListResponseModelDataAlerttypes.fromJson)
          .toList();
    } else if (alertdetails != null && alertdetails!.isNotEmpty) {
      final seen = <int>{};
      alerttypes = [];
      for (final alert in alertdetails!) {
        final id = alert?.AlertTypeID;
        if (id == null || seen.contains(id)) continue;
        seen.add(id);
        alerttypes!.add(AlertListResponseModelDataAlerttypes(
          AlertTypeID: id,
          AlertType: alert?.AlertType,
        ));
      }
    }

    final errorRaw = asListOrNull(json['error']);
    if (errorRaw != null) {
      error = asListOfMaps(errorRaw).map(DataError.fromJson).toList();
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (alertdetails != null) {
      final v = alertdetails;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['alertdetails'] = arr0;
    }
    if (alertcnt != null) {
      final v = alertcnt;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['alertcnt'] = arr0;
    }
    return data;
  }
}

class AlertListResponseModel with JsonSafeParser {
/*
{
  "data": {
    "status": 200,
    "alertdetails": [
      {
        "Id": 11,
        "AlertTypeID": 28,
        "AlertType": "yaccel end",
        "VehicleID": 190,
        "DriverID": null,
        "Alertdatetime": "2023-05-15 14:42:17",
        "Lat": 33.6992301940918,
        "Lon": 135.410842895508,
        "Location": " 和歌山県西牟婁郡上富田町朝来１９０１",
        "ignition": 0,
        "speed": 0,
        "direction": 0,
        "VehicleNo": "o6e2oohgkg",
        "Videofilepath": "1|RDovVnNzU2VydmljZS9odGRvY3MvdnNzRmlsZXMvYWxhcm1SZWNvcmQvMjAyM18wNV8xNS82MjA1NS9jaDAxXzIwMjMwNTE1XzE0NDIwN18xNDQyMjdfMDEyLmh3,2|RDovVnNzU2VydmljZS9odGRvY3MvdnNzRmlsZXMvYWxhcm1SZWNvcmQvMjAyM18wNV8xNS82MjA1NS9jaDAyXzIwMjMwNTE1XzE0NDIwN18xNDQyMjdfMDEyLmh3,3|RDovVnNzU2VydmljZS9odGRvY3MvdnNzRmlsZXMvYWxhcm1SZWNvcmQvMjAyM18wNV8xNS82MjA1NS9jaDAzXzIwMjMwNTE1XzE0NDIwN18xNDQyMjdfMDEyLmh3,4|RDovVnNzU2VydmljZS9odGRvY3MvdnNzRmlsZXMvYWxhcm1SZWNvcmQvMjAyM18wNV8xNS82MjA1NS9jaDA0XzIwMjMwNTE1XzE0NDIwN18xNDQyMjdfMDEyLmh3",
        "VFC": 4,
        "Status": "Alert",
        "Unitid": 6,
        "UnitNo": "62055",
        "drivername": ""
      }
    ],
    "alertcnt": [
      {
        "TotRec": 21
      }
    ]
  }
} 
*/

  AlertListResponseModelData? data;

  AlertListResponseModel({
    this.data,
  });
  AlertListResponseModel.fromJson(Map<String, dynamic> json) {
    final dataMap = asMapOrNull(json['data']);
    if (dataMap != null) {
      data = AlertListResponseModelData.fromJson(dataMap);
    } else {
      data = AlertListResponseModelData.fromJson(json);
    }
    }
  Map<String, dynamic> toJson() {
    final res = <String, dynamic>{};
    if (data != null) {
      res['data'] = data!.toJson();
    }
    return res;
  }
}


// ///
// /// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
// ///
// class AlertListResponseModelDataAlertdetails {
// /*
// {
//   "Id": 1,
//   "AlertTypeID": 10,
//   "AlertType": "Over Speed",
//   "VehicleID": 22,
//   "DriverID": null,
//   "Alertdatetime": "2023-04-20 18:35:07",
//   "Lat": 35.8001365661621,
//   "Lon": 140.359680175781,
//   "Location": "千葉県成田市十余三３０－５４",
//   "ignition": 0,
//   "speed": 0,
//   "direction": 0,
//   "VehicleNo": "72083",
//   "Videofilepath": "1|RDovVnNzU2VydmljZS9odGRvY3MvdnNzRmlsZXMvYWxhcm1SZWNvcmQvMjAyM18wNF8yMC83MjA4My9jaDAxXzIwMjMwNDIwXzE4MzQ1N18xODM1MTVfMDA3Lmh3,2|RDovVnNzU2VydmljZS9odGRvY3MvdnNzRmlsZXMvYWxhcm1SZWNvcmQvMjAyM18wNF8yMC83MjA4My9jaDAyXzIwMjMwNDIwXzE4MzQ1N18xODM1MTVfMDA3Lmh3,3|RDovVnNzU2VydmljZS9odGRvY3MvdnNzRmlsZXMvYWxhcm1SZWNvcmQvMjAyM18wNF8yMC83MjA4My9jaDAzXzIwMjMwNDIwXzE4MzQ1N18xODM1MTVfMDA3Lmh3,4|RDovVnNzU2VydmljZS9odGRvY3MvdnNzRmlsZXMvYWxhcm1SZWNvcmQvMjAyM18wNF8yMC83MjA4My9jaDA0XzIwMjMwNDIwXzE4MzQ1N18xODM1MTVfMDA3Lmh3",
//   "VFC": 4,
//   "Status": "Alert",
//   "Unitid": 22,
//   "UnitNo": "72083",
//   "drivername": ""
// } 
// */

//   int? Id;
//   int? AlertTypeID;
//   String? AlertType;
//   int? VehicleID;
//   String? DriverID;
//   String? Alertdatetime;
//   double? Lat;
//   double? Lon;
//   String? Location;
//   int? ignition;
//   int? speed;
//   int? direction;
//   String? VehicleNo;
//   String? Videofilepath;
//   int? VFC;
//   String? Status;
//   int? Unitid;
//   String? UnitNo;
//   String? drivername;

//   AlertListResponseModelDataAlertdetails({
//     this.Id,
//     this.AlertTypeID,
//     this.AlertType,
//     this.VehicleID,
//     this.DriverID,
//     this.Alertdatetime,
//     this.Lat,
//     this.Lon,
//     this.Location,
//     this.ignition,
//     this.speed,
//     this.direction,
//     this.VehicleNo,
//     this.Videofilepath,
//     this.VFC,
//     this.Status,
//     this.Unitid,
//     this.UnitNo,
//     this.drivername,
//   });
//   AlertListResponseModelDataAlertdetails.fromJson(Map<String, dynamic> json) {
//     Id = json['Id']?.toInt();
//     AlertTypeID = json['AlertTypeID']?.toInt();
//     AlertType = json['AlertType']?.toString();
//     VehicleID = json['VehicleID']?.toInt();
//     DriverID = json['DriverID']?.toString();
//     Alertdatetime = json['Alertdatetime']?.toString();
//     Lat = json['Lat']?.toDouble();
//     Lon = json['Lon']?.toDouble();
//     Location = json['Location']?.toString();
//     ignition = json['ignition']?.toInt();
//     speed = json['speed']?.toInt();
//     direction = json['direction']?.toInt();
//     VehicleNo = json['VehicleNo']?.toString();
//     Videofilepath = json['Videofilepath']?.toString();
//     VFC = json['VFC']?.toInt();
//     Status = json['Status']?.toString();
//     Unitid = json['Unitid']?.toInt();
//     UnitNo = json['UnitNo']?.toString();
//     drivername = json['drivername']?.toString();
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['Id'] = Id;
//     data['AlertTypeID'] = AlertTypeID;
//     data['AlertType'] = AlertType;
//     data['VehicleID'] = VehicleID;
//     data['DriverID'] = DriverID;
//     data['Alertdatetime'] = Alertdatetime;
//     data['Lat'] = Lat;
//     data['Lon'] = Lon;
//     data['Location'] = Location;
//     data['ignition'] = ignition;
//     data['speed'] = speed;
//     data['direction'] = direction;
//     data['VehicleNo'] = VehicleNo;
//     data['Videofilepath'] = Videofilepath;
//     data['VFC'] = VFC;
//     data['Status'] = Status;
//     data['Unitid'] = Unitid;
//     data['UnitNo'] = UnitNo;
//     data['drivername'] = drivername;
//     return data;
//   }
// }

// class AlertListResponseModelData {
// /*
// {
//   "status": 200,
//   "alertdetails": [
//     {
//       "Id": 1,
//       "AlertTypeID": 10,
//       "AlertType": "Over Speed",
//       "VehicleID": 22,
//       "DriverID": null,
//       "Alertdatetime": "2023-04-20 18:35:07",
//       "Lat": 35.8001365661621,
//       "Lon": 140.359680175781,
//       "Location": "千葉県成田市十余三３０－５４",
//       "ignition": 0,
//       "speed": 0,
//       "direction": 0,
//       "VehicleNo": "72083",
//       "Videofilepath": "1|RDovVnNzU2VydmljZS9odGRvY3MvdnNzRmlsZXMvYWxhcm1SZWNvcmQvMjAyM18wNF8yMC83MjA4My9jaDAxXzIwMjMwNDIwXzE4MzQ1N18xODM1MTVfMDA3Lmh3,2|RDovVnNzU2VydmljZS9odGRvY3MvdnNzRmlsZXMvYWxhcm1SZWNvcmQvMjAyM18wNF8yMC83MjA4My9jaDAyXzIwMjMwNDIwXzE4MzQ1N18xODM1MTVfMDA3Lmh3,3|RDovVnNzU2VydmljZS9odGRvY3MvdnNzRmlsZXMvYWxhcm1SZWNvcmQvMjAyM18wNF8yMC83MjA4My9jaDAzXzIwMjMwNDIwXzE4MzQ1N18xODM1MTVfMDA3Lmh3,4|RDovVnNzU2VydmljZS9odGRvY3MvdnNzRmlsZXMvYWxhcm1SZWNvcmQvMjAyM18wNF8yMC83MjA4My9jaDA0XzIwMjMwNDIwXzE4MzQ1N18xODM1MTVfMDA3Lmh3",
//       "VFC": 4,
//       "Status": "Alert",
//       "Unitid": 22,
//       "UnitNo": "72083",
//       "drivername": ""
//     }
//   ]
// } 
// */

//   int? status;
//   List<AlertListResponseModelDataAlertdetails?>? alertdetails;
//   List<DataError?>? error;

//   AlertListResponseModelData({this.status, this.alertdetails, this.error});
//   AlertListResponseModelData.fromJson(Map<String, dynamic> json) {
//     status = json['status']?.toInt();
//     if (json['alertdetails'] != null) {
//       final v = json['alertdetails'];
//       final arr0 = <AlertListResponseModelDataAlertdetails>[];
//       v.forEach((v) {
//         arr0.add(AlertListResponseModelDataAlertdetails.fromJson(v));
//       });
//       alertdetails = arr0;
//     }
    // if (json['error'] != null) {
    //   final v = json['error'];
    //   final arr0 = <DataError>[];
    //   v.forEach((v) {
    //     arr0.add(DataError.fromJson(v));
    //   });
    //   error = arr0;
    // }
  // }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['status'] = status;
//     if (alertdetails != null) {
//       final v = alertdetails;
//       final arr0 = [];
//       v!.forEach((v) {
//         arr0.add(v!.toJson());
//       });
//       data['alertdetails'] = arr0;
//     }
//     return data;
//   }
// }

// class AlertListResponseModel {
// /*
// {
//   "data": {
//     "status": 200,
//     "alertdetails": [
//       {
//         "Id": 1,
//         "AlertTypeID": 10,
//         "AlertType": "Over Speed",
//         "VehicleID": 22,
//         "DriverID": null,
//         "Alertdatetime": "2023-04-20 18:35:07",
//         "Lat": 35.8001365661621,
//         "Lon": 140.359680175781,
//         "Location": "千葉県成田市十余三３０－５４",
//         "ignition": 0,
//         "speed": 0,
//         "direction": 0,
//         "VehicleNo": "72083",
//         "Videofilepath": "1|RDovVnNzU2VydmljZS9odGRvY3MvdnNzRmlsZXMvYWxhcm1SZWNvcmQvMjAyM18wNF8yMC83MjA4My9jaDAxXzIwMjMwNDIwXzE4MzQ1N18xODM1MTVfMDA3Lmh3,2|RDovVnNzU2VydmljZS9odGRvY3MvdnNzRmlsZXMvYWxhcm1SZWNvcmQvMjAyM18wNF8yMC83MjA4My9jaDAyXzIwMjMwNDIwXzE4MzQ1N18xODM1MTVfMDA3Lmh3,3|RDovVnNzU2VydmljZS9odGRvY3MvdnNzRmlsZXMvYWxhcm1SZWNvcmQvMjAyM18wNF8yMC83MjA4My9jaDAzXzIwMjMwNDIwXzE4MzQ1N18xODM1MTVfMDA3Lmh3,4|RDovVnNzU2VydmljZS9odGRvY3MvdnNzRmlsZXMvYWxhcm1SZWNvcmQvMjAyM18wNF8yMC83MjA4My9jaDA0XzIwMjMwNDIwXzE4MzQ1N18xODM1MTVfMDA3Lmh3",
//         "VFC": 4,
//         "Status": "Alert",
//         "Unitid": 22,
//         "UnitNo": "72083",
//         "drivername": ""
//       }
//     ]
//   }
// } 
// */

//   AlertListResponseModelData? data;

//   AlertListResponseModel({
//     this.data,
//   });
//   AlertListResponseModel.fromJson(Map<String, dynamic> json) {
//     data = (json['data'] != null)
//         ? AlertListResponseModelData.fromJson(json['data'])
//         : null;
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['data'] = this.data!.toJson();
//     return data;
//   }
// }
