import '../../../utils/json_safe_parser.dart';
import '../../login/model/client_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
// ignore_for_file: non_constant_identifier_names

class ForgotPasswordResponseModelDataData with JsonSafeParser {
/*
{
  "ResultID": 1,
  "ResultMessage": "User exsits",
  "Userid": 1,
  "Username": "Infotrack",
  "Authword": "infoadmin",
  "EmailId": "shrinath@infotracktelematics.com"
} 
*/

  int? ResultID;
  String? ResultMessage;
  int? Userid;
  String? Username;
  String? Authword;
  String? EmailId;

  ForgotPasswordResponseModelDataData({
    this.ResultID,
    this.ResultMessage,
    this.Userid,
    this.Username,
    this.Authword,
    this.EmailId,
  });
  ForgotPasswordResponseModelDataData.fromJson(Map<String, dynamic> json) {
    ResultID = JsonSafe.asIntOrNull(
      JsonSafe.firstValue(json, ['ResultID', 'resultId', 'ResultId']),
    );
    ResultMessage = asStringFrom(json, ['ResultMessage', 'resultMessage']);
    Userid = JsonSafe.asIntOrNull(
      JsonSafe.firstValue(json, ['Userid', 'userid', 'UserId']),
    );
    Username = asStringFrom(json, ['Username', 'username']);
    Authword = asStringFrom(json, ['Authword', 'authword']);
    EmailId = asStringFrom(json, ['EmailId', 'emailId']);
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ResultID'] = ResultID;
    data['ResultMessage'] = ResultMessage;
    data['Userid'] = Userid;
    data['Username'] = Username;
    data['Authword'] = Authword;
    data['EmailId'] = EmailId;
    return data;
  }
}

class ForgotPasswordResponseModelData with JsonSafeParser {
/*
{
  "status": 200,
  "data": {
    "ResultID": 1,
    "ResultMessage": "User exsits",
    "Userid": 1,
    "Username": "Infotrack",
    "Authword": "infoadmin",
    "EmailId": "shrinath@infotracktelematics.com"
  },
  "message": "Email sent successfully"
} 
*/

  int? status;
  ForgotPasswordResponseModelDataData? data;
  String? message;
  List<DataError?>? error;

  ForgotPasswordResponseModelData({
    this.status,
    this.data,
    this.message,
  });
  ForgotPasswordResponseModelData.fromJson(Map<String, dynamic> json) {
    status = asIntFrom(json, ['status', 'Status']);
    message = asStringFrom(json, ['message', 'Message']);
    data = _resultRow(json['data'] ?? json['Data']);
  }

  static ForgotPasswordResponseModelDataData? _resultRow(dynamic raw) {
    if (raw is List) {
      for (final item in raw) {
        if (item is Map) {
          return ForgotPasswordResponseModelDataData.fromJson(
            Map<String, dynamic>.from(item),
          );
        }
      }
      return null;
    }
    final inner = JsonSafe.asMapOrNull(raw);
    if (inner == null || inner.isEmpty) return null;
    return ForgotPasswordResponseModelDataData.fromJson(inner);
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['data'] = this.data!.toJson();
    data['message'] = message;
    return data;
  }
}

class ForgotPasswordResponseModel with JsonSafeParser {
/*
{
  "data": {
    "status": 200,
    "data": {
      "ResultID": 1,
      "ResultMessage": "User exsits",
      "Userid": 1,
      "Username": "Infotrack",
      "Authword": "infoadmin",
      "EmailId": "shrinath@infotracktelematics.com"
    },
    "message": "Email sent successfully"
  }
} 
*/

  ForgotPasswordResponseModelData? data;

  ForgotPasswordResponseModel({
    this.data,
  });
  ForgotPasswordResponseModel.fromJson(Map<String, dynamic> json) {
    final dataMap = asMapOrNull(json['data']);
    if (dataMap != null) {
      data = ForgotPasswordResponseModelData.fromJson(dataMap);
    } else {
      data = ForgotPasswordResponseModelData.fromJson(json);
    }
  }

  /// User exists and the reset mail can be shown.
  ///
  /// Sequel returns `status: 1` and `message: Success` for both a real user
  /// and a missing user. [ResultID] `1` means the user exists; `0` does not.
  bool get isSuccess {
    final resultId = data?.data?.ResultID;
    if (resultId != null) return resultId > 0;
    final status = data?.status;
    final msg = '${data?.message ?? ''} ${data?.data?.ResultMessage ?? ''}'
        .toLowerCase();
    if (msg.contains('not') &&
        (msg.contains('exist') || msg.contains('exsit'))) {
      return false;
    }
    if (status == 1 || status == 200) return true;
    if (msg.contains('success') ||
        msg.contains('sent') ||
        msg.contains('updated') ||
        msg.contains('reset')) {
      return true;
    }
    return false;
  }

  String get failureMessage {
    final resultMessage = (data?.data?.ResultMessage ?? '').trim();
    final lower = resultMessage.toLowerCase();
    if (lower.contains('not') &&
        (lower.contains('exist') || lower.contains('exsit'))) {
      return resultMessage;
    }
    if (resultMessage.isNotEmpty && (data?.data?.ResultID ?? 1) <= 0) {
      return resultMessage;
    }
    final message = (data?.message ?? '').trim();
    if (message.isNotEmpty && message.toLowerCase() != 'success') {
      return message;
    }
    return resultMessage;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data!.toJson();
    return data;
  }
}
