import '../../login/model/client_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
// ignore_for_file: non_constant_identifier_names

class ForgotPasswordResponseModelDataData {
/*
{
  "ResultID": 1,
  "ResultMessage": "User exsits",
  "Userid": 1,
  "Username": "Infotrack",
  "Authword": "infoadmin",
  "EmailId": "shrinath@infotracktelematics.com"
} 
*/

  int? ResultID;
  String? ResultMessage;
  int? Userid;
  String? Username;
  String? Authword;
  String? EmailId;

  ForgotPasswordResponseModelDataData({
    this.ResultID,
    this.ResultMessage,
    this.Userid,
    this.Username,
    this.Authword,
    this.EmailId,
  });
  ForgotPasswordResponseModelDataData.fromJson(Map<String, dynamic> json) {
    ResultID = json['ResultID']?.toInt();
    ResultMessage = json['ResultMessage']?.toString();
    Userid = json['Userid']?.toInt();
    Username = json['Username']?.toString();
    Authword = json['Authword']?.toString();
    EmailId = json['EmailId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ResultID'] = ResultID;
    data['ResultMessage'] = ResultMessage;
    data['Userid'] = Userid;
    data['Username'] = Username;
    data['Authword'] = Authword;
    data['EmailId'] = EmailId;
    return data;
  }
}

class ForgotPasswordResponseModelData {
/*
{
  "status": 200,
  "data": {
    "ResultID": 1,
    "ResultMessage": "User exsits",
    "Userid": 1,
    "Username": "Infotrack",
    "Authword": "infoadmin",
    "EmailId": "shrinath@infotracktelematics.com"
  },
  "message": "Email sent successfully"
} 
*/

  int? status;
  ForgotPasswordResponseModelDataData? data;
  String? message;
  List<DataError?>? error;

  ForgotPasswordResponseModelData({
    this.status,
    this.data,
    this.message,
  });
  ForgotPasswordResponseModelData.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    data = (json['data'] != null)
        ? ForgotPasswordResponseModelDataData.fromJson(json['data'])
        : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['data'] = this.data!.toJson();
    data['message'] = message;
    return data;
  }
}

class ForgotPasswordResponseModel {
/*
{
  "data": {
    "status": 200,
    "data": {
      "ResultID": 1,
      "ResultMessage": "User exsits",
      "Userid": 1,
      "Username": "Infotrack",
      "Authword": "infoadmin",
      "EmailId": "shrinath@infotracktelematics.com"
    },
    "message": "Email sent successfully"
  }
} 
*/

  ForgotPasswordResponseModelData? data;

  ForgotPasswordResponseModel({
    this.data,
  });
  ForgotPasswordResponseModel.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? ForgotPasswordResponseModelData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data!.toJson();
    return data;
  }
}
