import '../../../utils/json_safe_parser.dart';
import '../../login/model/client_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
// ignore_for_file: non_constant_identifier_names

class ForgotPasswordResponseModelDataData with JsonSafeParser {
/*
{
  "ResultID": 1,
  "ResultMessage": "User exsits",
  "Userid": 1,
  "Username": "Infotrack",
  "Authword": "infoadmin",
  "EmailId": "shrinath@infotracktelematics.com"
} 
*/

  int? ResultID;
  String? ResultMessage;
  int? Userid;
  String? Username;
  String? Authword;
  String? EmailId;

  ForgotPasswordResponseModelDataData({
    this.ResultID,
    this.ResultMessage,
    this.Userid,
    this.Username,
    this.Authword,
    this.EmailId,
  });
  ForgotPasswordResponseModelDataData.fromJson(Map<String, dynamic> json) {
    ResultID = asInt(json['ResultID']);
    ResultMessage = asString(json['ResultMessage']);
    Userid = asInt(json['Userid']);
    Username = asString(json['Username']);
    Authword = asString(json['Authword']);
    EmailId = asString(json['EmailId']);
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ResultID'] = ResultID;
    data['ResultMessage'] = ResultMessage;
    data['Userid'] = Userid;
    data['Username'] = Username;
    data['Authword'] = Authword;
    data['EmailId'] = EmailId;
    return data;
  }
}

class ForgotPasswordResponseModelData with JsonSafeParser {
/*
{
  "status": 200,
  "data": {
    "ResultID": 1,
    "ResultMessage": "User exsits",
    "Userid": 1,
    "Username": "Infotrack",
    "Authword": "infoadmin",
    "EmailId": "shrinath@infotracktelematics.com"
  },
  "message": "Email sent successfully"
} 
*/

  int? status;
  ForgotPasswordResponseModelDataData? data;
  String? message;
  List<DataError?>? error;

  ForgotPasswordResponseModelData({
    this.status,
    this.data,
    this.message,
  });
  ForgotPasswordResponseModelData.fromJson(Map<String, dynamic> json) {
    status = asIntFrom(json, ['status', 'Status']);
    final inner = asMapOrNull(json['data']);
    data = inner != null
        ? ForgotPasswordResponseModelDataData.fromJson(inner)
        : null;
    message = asStringFrom(json, ['message', 'Message']);
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['data'] = this.data!.toJson();
    data['message'] = message;
    return data;
  }
}

class ForgotPasswordResponseModel with JsonSafeParser {
/*
{
  "data": {
    "status": 200,
    "data": {
      "ResultID": 1,
      "ResultMessage": "User exsits",
      "Userid": 1,
      "Username": "Infotrack",
      "Authword": "infoadmin",
      "EmailId": "shrinath@infotracktelematics.com"
    },
    "message": "Email sent successfully"
  }
} 
*/

  ForgotPasswordResponseModelData? data;

  ForgotPasswordResponseModel({
    this.data,
  });
  ForgotPasswordResponseModel.fromJson(Map<String, dynamic> json) {
    final dataMap = asMapOrNull(json['data']);
    if (dataMap != null) {
      data = ForgotPasswordResponseModelData.fromJson(dataMap);
    } else {
      data = ForgotPasswordResponseModelData.fromJson(json);
    }
  }

  bool get isSuccess {
    final status = data?.status;
    return status == 1 || status == 200;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data!.toJson();
    return data;
  }
}
