import '../../../utils/json_safe_parser.dart';
import '../../login/model/client_model.dart';

List<dynamic>? _extractVehicleDetails(Map<String, dynamic> json) {
  const listKeys = [
    'vehicledetails',
    'vehicleDetails',
    'vehicleStatusdetails',
    'vehicles',
    'vehicleList',
    'pinvehicle',
    'Pinvehicle',
  ];
  final fromKeys = JsonSafe.asListOrNull(JsonSafe.firstValue(json, listKeys));
  if (fromKeys != null) return fromKeys;
  final nested = JsonSafe.firstValue(json, ['data', 'Data']);
  final nestedList = JsonSafe.asListOrNull(nested);
  if (nestedList != null) return nestedList;
  final nestedMap = JsonSafe.asMapOrNull(nested);
  if (nestedMap != null) return _extractVehicleDetails(nestedMap);
  return null;
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DynamicStatusModelDataVehicleCnt with JsonSafeParser {
/*
{
  "reccount": 10
} 
*/

  int? reccount;

  DynamicStatusModelDataVehicleCnt({
    this.reccount,
  });
  DynamicStatusModelDataVehicleCnt.fromJson(Map<String, dynamic> json) {
    reccount = asIntFrom(json, [
      'reccount',
      'recCount',
      'recCnt',
      'RecCnt',
      'totRec',
    ]);
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['reccount'] = reccount;
    return data;
  }
}

class DynamicStatusModelDataVehicledetails with JsonSafeParser {
/*
{
  "id": 1,
  "VehicleId": 188,
  "VehicleNo": "Truck 2",
  "TrackingTime": "Jul 31 2023  6:02AM",
  "Location": "4479-4301 Mason St, South Gate, CA 90280",
  "speed": 0,
  "ignition": "On",
  "odometer": 19534.49,
  "Status": "Idle",
  "DelayEnable": 90,
  "LiveUrl": "https://earthsupportlivevideo.infotracktelematics.com:9965/vss/apiPage/RealVideo.html?token==21232f297a57a5a743894a0e4a801fc3&deviceId=75006&chs=1_2_3_4&stream=0&wnum=4&panel=1",
  "Mapit": "33.9536,-118.192",
  "deviceType": "MDVR"
} 
*/

  int? id;
  int? VehicleId;
  String? VehicleNo;
  String? TrackingTime;
  String? Location;
  int? speed;
  String? ignition;
  double? odometer;
  String? Status;
  int? DelayEnable;
  String? LiveUrl;
  String? Mapit;
  int? Idleduration;
  String? deviceType;

  DynamicStatusModelDataVehicledetails({
    this.id,
    this.VehicleId,
    this.VehicleNo,
    this.TrackingTime,
    this.Location,
    this.speed,
    this.ignition,
    this.odometer,
    this.Status,
    this.DelayEnable,
    this.LiveUrl,
    this.Mapit,
    this.Idleduration,
    this.deviceType
  });
  DynamicStatusModelDataVehicledetails.fromJson(Map<String, dynamic> json) {
    id = asInt(json['id']);
    VehicleId = asIntFrom(json, [
      'VehicleId',
      'vehicleId',
      'Vehicleid',
      'VehicleID',
    ]);
    VehicleNo = asStringFrom(json, ['VehicleNo', 'vehicleNo']);
    TrackingTime = asStringFrom(json, [
      'TrackingTime',
      'trackingTime',
      'tracktime',
      'trackTime',
    ]);
    Location = asStringFrom(json, ['Location', 'location']);
    speed = asInt(json['speed']);
    ignition = asString(json['ignition']);
    odometer = asDouble(json['odometer']);
    Status = asStringFrom(json, ['Status', 'status']);
    DelayEnable = asIntFrom(json, ['DelayEnable', 'delayEnable']);
    LiveUrl = asStringFrom(json, ['LiveUrl', 'liveUrl']);
    Mapit = asStringFrom(json, ['Mapit', 'mapit', 'mapIt']);
    Idleduration =
        asIntFrom(json, ['Idleduration', 'idleduration', 'idleDuration']);
    deviceType = asStringFrom(json, ['devicetype', 'deviceType']);
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['VehicleId'] = VehicleId;
    data['VehicleNo'] = VehicleNo;
    data['TrackingTime'] = TrackingTime;
    data['Location'] = Location;
    data['speed'] = speed;
    data['ignition'] = ignition;
    data['odometer'] = odometer;
    data['Status'] = Status;
    data['DelayEnable'] = DelayEnable;
    data['LiveUrl'] = LiveUrl;
    data['Mapit'] = Mapit;
    data['devicetype'] = deviceType;
    return data;
  }
}

class DynamicStatusModelData with JsonSafeParser {
/*
{
  "status": 200,
  "vehicledetails": [
    {
      "id": 1,
      "VehicleId": 188,
      "VehicleNo": "Truck 2",
      "TrackingTime": "Jul 31 2023  6:02AM",
      "Location": "4479-4301 Mason St, South Gate, CA 90280",
      "speed": 0,
      "ignition": "On",
      "odometer": 19534.49,
      "Status": "Idle",
      "DelayEnable": 90,
      "LiveUrl": "https://earthsupportlivevideo.infotracktelematics.com:9965/vss/apiPage/RealVideo.html?token==21232f297a57a5a743894a0e4a801fc3&deviceId=75006&chs=1_2_3_4&stream=0&wnum=4&panel=1",
      "Mapit": "33.9536,-118.192"
    }
  ],
  "vehicleCnt": [
    {
      "reccount": 10
    }
  ]
} 
*/

  int? status;
  List<DynamicStatusModelDataVehicledetails?>? vehicledetails;
  List<DynamicStatusModelDataVehicleCnt?>? vehicleCnt;
  List<DataError?>? error;
  DynamicStatusModelData({
    this.status,
    this.vehicledetails,
    this.vehicleCnt,
  });
  DynamicStatusModelData.fromJson(Map<String, dynamic> json) {
    status = asIntFrom(json, ['status', 'Status']);
    final detailsRaw = _extractVehicleDetails(json);
    if (detailsRaw != null) {
      vehicledetails = asListOfMaps(detailsRaw)
          .map(DynamicStatusModelDataVehicledetails.fromJson)
          .toList();
    }
    final nestedData = asMapOrNull(json['data']);
    final countRaw = asListOrNull(firstValue(json, [
          'vehicleCnt',
          'vehicleCount',
          'VehicleCnt',
        ])) ??
        asListOrNull(firstValue(nestedData ?? const {}, [
          'vehicleCnt',
          'vehicleCount',
        ]));
    if (countRaw != null) {
      vehicleCnt = asListOfMaps(countRaw)
          .map(DynamicStatusModelDataVehicleCnt.fromJson)
          .toList();
    } else {
      final rec = asIntOrNull(firstValue(json, [
        'reccount',
        'recCount',
        'recCnt',
        'totalCount',
      ]));
      if (rec != null) {
        vehicleCnt = [DynamicStatusModelDataVehicleCnt(reccount: rec)];
      }
    }
    final errorRaw = asListOrNull(json['error']);
    if (errorRaw != null) {
      error = asListOfMaps(errorRaw).map(DataError.fromJson).toList();
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (vehicledetails != null) {
      final v = vehicledetails;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['vehicledetails'] = arr0;
    }
    if (vehicleCnt != null) {
      final v = vehicleCnt;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['vehicleCnt'] = arr0;
    }
    return data;
  }
}

class DynamicStatusModel with JsonSafeParser {
/*
{
  "data": {
    "status": 200,
    "vehicledetails": [
      {
        "id": 1,
        "VehicleId": 188,
        "VehicleNo": "Truck 2",
        "TrackingTime": "Jul 31 2023  6:02AM",
        "Location": "4479-4301 Mason St, South Gate, CA 90280",
        "speed": 0,
        "ignition": "On",
        "odometer": 19534.49,
        "Status": "Idle",
        "DelayEnable": 90,
        "LiveUrl": "https://earthsupportlivevideo.infotracktelematics.com:9965/vss/apiPage/RealVideo.html?token==21232f297a57a5a743894a0e4a801fc3&deviceId=75006&chs=1_2_3_4&stream=0&wnum=4&panel=1",
        "Mapit": "33.9536,-118.192",
        "deviceType": "MDVR"
      }
    ],
    "vehicleCnt": [
      {
        "reccount": 10
      }
    ]
  }
} 
*/

  DynamicStatusModelData? data;

  DynamicStatusModel({
    this.data,
  });
  DynamicStatusModel.fromJson(Map<String, dynamic> json) {
    final dataMap = asMapOrNull(json['data']);
    if (dataMap != null) {
      data = DynamicStatusModelData.fromJson(dataMap);
    } else {
      data = DynamicStatusModelData.fromJson(json);
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data!.toJson();
    return data;
  }
}
