import '../../login/model/client_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DynamicStatusModelDataVehicleCnt {
/*
{
  "reccount": 10
} 
*/

  int? reccount;

  DynamicStatusModelDataVehicleCnt({
    this.reccount,
  });
  DynamicStatusModelDataVehicleCnt.fromJson(Map<String, dynamic> json) {
    reccount = json['reccount']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['reccount'] = reccount;
    return data;
  }
}

class DynamicStatusModelDataVehicledetails {
/*
{
  "id": 1,
  "VehicleId": 188,
  "VehicleNo": "Truck 2",
  "TrackingTime": "Jul 31 2023  6:02AM",
  "Location": "4479-4301 Mason St, South Gate, CA 90280",
  "speed": 0,
  "ignition": "On",
  "odometer": 19534.49,
  "Status": "Idle",
  "DelayEnable": 90,
  "LiveUrl": "https://earthsupportlivevideo.infotracktelematics.com:9965/vss/apiPage/RealVideo.html?token==21232f297a57a5a743894a0e4a801fc3&deviceId=75006&chs=1_2_3_4&stream=0&wnum=4&panel=1",
  "Mapit": "33.9536,-118.192",
  "deviceType": "MDVR"
} 
*/

  int? id;
  int? VehicleId;
  String? VehicleNo;
  String? TrackingTime;
  String? Location;
  int? speed;
  String? ignition;
  double? odometer;
  String? Status;
  int? DelayEnable;
  String? LiveUrl;
  String? Mapit;
  int? Idleduration;
  String? deviceType;

  DynamicStatusModelDataVehicledetails({
    this.id,
    this.VehicleId,
    this.VehicleNo,
    this.TrackingTime,
    this.Location,
    this.speed,
    this.ignition,
    this.odometer,
    this.Status,
    this.DelayEnable,
    this.LiveUrl,
    this.Mapit,
    this.Idleduration,
    this.deviceType
  });
  DynamicStatusModelDataVehicledetails.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    VehicleId = json['VehicleId']?.toInt();
    VehicleNo = json['VehicleNo']?.toString();
    TrackingTime = json['TrackingTime']?.toString();
    Location = json['Location']?.toString();
    speed = json['speed']?.toInt();
    ignition = json['ignition']?.toString();
    odometer = json['odometer']?.toDouble();
    Status = json['Status']?.toString();
    DelayEnable = json['DelayEnable']?.toInt();
    LiveUrl = json['LiveUrl']?.toString();
    Mapit = json['Mapit']?.toString();
    Idleduration = json['Idleduration']?.toInt();
    deviceType = json['devicetype'] ?? "";
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['VehicleId'] = VehicleId;
    data['VehicleNo'] = VehicleNo;
    data['TrackingTime'] = TrackingTime;
    data['Location'] = Location;
    data['speed'] = speed;
    data['ignition'] = ignition;
    data['odometer'] = odometer;
    data['Status'] = Status;
    data['DelayEnable'] = DelayEnable;
    data['LiveUrl'] = LiveUrl;
    data['Mapit'] = Mapit;
    data['devicetype'] = deviceType;
    return data;
  }
}

class DynamicStatusModelData {
/*
{
  "status": 200,
  "vehicledetails": [
    {
      "id": 1,
      "VehicleId": 188,
      "VehicleNo": "Truck 2",
      "TrackingTime": "Jul 31 2023  6:02AM",
      "Location": "4479-4301 Mason St, South Gate, CA 90280",
      "speed": 0,
      "ignition": "On",
      "odometer": 19534.49,
      "Status": "Idle",
      "DelayEnable": 90,
      "LiveUrl": "https://earthsupportlivevideo.infotracktelematics.com:9965/vss/apiPage/RealVideo.html?token==21232f297a57a5a743894a0e4a801fc3&deviceId=75006&chs=1_2_3_4&stream=0&wnum=4&panel=1",
      "Mapit": "33.9536,-118.192"
    }
  ],
  "vehicleCnt": [
    {
      "reccount": 10
    }
  ]
} 
*/

  int? status;
  List<DynamicStatusModelDataVehicledetails?>? vehicledetails;
  List<DynamicStatusModelDataVehicleCnt?>? vehicleCnt;
  List<DataError?>? error;
  DynamicStatusModelData({
    this.status,
    this.vehicledetails,
    this.vehicleCnt,
  });
  DynamicStatusModelData.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    if (json['vehicledetails'] != null) {
      final v = json['vehicledetails'];
      final arr0 = <DynamicStatusModelDataVehicledetails>[];
      v.forEach((v) {
        arr0.add(DynamicStatusModelDataVehicledetails.fromJson(v));
      });
      vehicledetails = arr0;
    }
    if (json['vehicleCnt'] != null) {
      final v = json['vehicleCnt'];
      final arr0 = <DynamicStatusModelDataVehicleCnt>[];
      v.forEach((v) {
        arr0.add(DynamicStatusModelDataVehicleCnt.fromJson(v));
      });
      vehicleCnt = arr0;
    }
    if (json['error'] != null) {
      final v = json['error'];
      final arr0 = <DataError>[];
      v.forEach((v) {
        arr0.add(DataError.fromJson(v));
      });
      error = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (vehicledetails != null) {
      final v = vehicledetails;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['vehicledetails'] = arr0;
    }
    if (vehicleCnt != null) {
      final v = vehicleCnt;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['vehicleCnt'] = arr0;
    }
    return data;
  }
}

class DynamicStatusModel {
/*
{
  "data": {
    "status": 200,
    "vehicledetails": [
      {
        "id": 1,
        "VehicleId": 188,
        "VehicleNo": "Truck 2",
        "TrackingTime": "Jul 31 2023  6:02AM",
        "Location": "4479-4301 Mason St, South Gate, CA 90280",
        "speed": 0,
        "ignition": "On",
        "odometer": 19534.49,
        "Status": "Idle",
        "DelayEnable": 90,
        "LiveUrl": "https://earthsupportlivevideo.infotracktelematics.com:9965/vss/apiPage/RealVideo.html?token==21232f297a57a5a743894a0e4a801fc3&deviceId=75006&chs=1_2_3_4&stream=0&wnum=4&panel=1",
        "Mapit": "33.9536,-118.192",
        "deviceType": "MDVR"
      }
    ],
    "vehicleCnt": [
      {
        "reccount": 10
      }
    ]
  }
} 
*/

  DynamicStatusModelData? data;

  DynamicStatusModel({
    this.data,
  });
  DynamicStatusModel.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? DynamicStatusModelData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data!.toJson();
    return data;
  }
}
