import '../../login/model/client_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PinVehicleResponseModelDataPinvehicle {
/*
{
  "Resultid": "1",
  "Remark": "Vehicle added Sucessfully"
} 
*/

  String? Resultid;
  String? Remark;

  PinVehicleResponseModelDataPinvehicle({
    this.Resultid,
    this.Remark,
  });
  PinVehicleResponseModelDataPinvehicle.fromJson(Map<String, dynamic> json) {
    Resultid = json['Resultid']?.toString();
    Remark = json['Remark']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Resultid'] = Resultid;
    data['Remark'] = Remark;
    return data;
  }
}

class PinVehicleResponseModelData {
/*
{
  "status": 200,
  "pinvehicle": [
    {
      "Resultid": "1",
      "Remark": "Vehicle added Sucessfully"
    }
  ]
} 
*/

  int? status;
  List<PinVehicleResponseModelDataPinvehicle?>? pinvehicle;

  List<DataError?>? error;

  PinVehicleResponseModelData({
    this.status,
    this.pinvehicle,
  });
  PinVehicleResponseModelData.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    if (json['pinvehicle'] != null) {
      final v = json['pinvehicle'];
      final arr0 = <PinVehicleResponseModelDataPinvehicle>[];
      v.forEach((v) {
        arr0.add(PinVehicleResponseModelDataPinvehicle.fromJson(v));
      });
      pinvehicle = arr0;
    }
    if (json['error'] != null) {
      final v = json['error'];
      final arr0 = <DataError>[];
      v.forEach((v) {
        arr0.add(DataError.fromJson(v));
      });
      error = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (pinvehicle != null) {
      final v = pinvehicle;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['pinvehicle'] = arr0;
    }
    return data;
  }
}

class PinVehicleResponseModel {
/*
{
  "data": {
    "status": 200,
    "pinvehicle": [
      {
        "Resultid": "1",
        "Remark": "Vehicle added Sucessfully"
      }
    ]
  }
} 
*/

  PinVehicleResponseModelData? data;

  PinVehicleResponseModel({
    this.data,
  });
  PinVehicleResponseModel.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? PinVehicleResponseModelData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data!.toJson();
    return data;
  }
}
