import '../../../utils/json_safe_parser.dart';
import '../../login/model/client_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PinVehicleResponseModelDataPinvehicle with JsonSafeParser {
/*
{
  "Resultid": "1",
  "Remark": "Vehicle added Sucessfully"
} 
*/

  String? Resultid;
  String? Remark;

  PinVehicleResponseModelDataPinvehicle({
    this.Resultid,
    this.Remark,
  });
  PinVehicleResponseModelDataPinvehicle.fromJson(Map<String, dynamic> json) {
    Resultid = asStringFrom(json, ['Resultid', 'resultId']);
    Remark = asStringFrom(json, ['Remark', 'remark']);
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Resultid'] = Resultid;
    data['Remark'] = Remark;
    return data;
  }
}

class PinVehicleResponseModelData with JsonSafeParser {
/*
{
  "status": 200,
  "pinvehicle": [
    {
      "Resultid": "1",
      "Remark": "Vehicle added Sucessfully"
    }
  ]
} 
*/

  int? status;
  String? message;
  List<PinVehicleResponseModelDataPinvehicle?>? pinvehicle;

  List<DataError?>? error;

  PinVehicleResponseModelData({
    this.status,
    this.message,
    this.pinvehicle,
  });
  PinVehicleResponseModelData.fromJson(Map<String, dynamic> json) {
    status = asIntFrom(json, ['status', 'Status']);
    message = asStringFrom(json, ['message', 'Message']);
    pinvehicle = asListOfMaps(firstValue(json, [
      'pinvehicle',
      'pinVehicle',
      'Pinvehicle',
    ]))
        .map(PinVehicleResponseModelDataPinvehicle.fromJson)
        .toList();
    error = asListOfMaps(firstValue(json, ['error', 'Error']))
        .map(DataError.fromJson)
        .toList();
  }

  bool get isSuccess => status == 1 || status == 200;
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (pinvehicle != null) {
      final v = pinvehicle;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['pinvehicle'] = arr0;
    }
    return data;
  }
}

class PinVehicleResponseModel with JsonSafeParser {
/*
{
  "data": {
    "status": 200,
    "pinvehicle": [
      {
        "Resultid": "1",
        "Remark": "Vehicle added Sucessfully"
      }
    ]
  }
} 
*/

  PinVehicleResponseModelData? data;

  PinVehicleResponseModel({
    this.data,
  });
  PinVehicleResponseModel.fromJson(Map<String, dynamic> json) {
    final dataMap = asMapOrNull(json['data']);
    if (dataMap != null) {
      data = PinVehicleResponseModelData.fromJson(dataMap);
    } else {
      data = PinVehicleResponseModelData.fromJson(json);
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data!.toJson();
    return data;
  }
}
